### ISSUE TITLE
Order penalties by Rules / Cues

### ISSUE THREAD

**Issue by admdikramr** [rollerderby/scoreboard#142]
Feedback from the Kalamazoo Continental Cup (I was CHNSO and used CRG for PT): Feature request for the "choose which penalty" screen to be in the order of the ruleset. Currently it is alphabetical. Some people may prefer alphabetical so this could perhaps be an option.

Ruleset order would still be three rows:

      (B) (A) (L) | (H) (F) (E)
         (D) (C) (M) | (P) (X)
              (N) (I) (G)

**Comment by brian-brazil** [comment]
That'd be quite challenging to implement, as that's not just an arbitrary ordering that has to be plumbed though from somewhere but also arbitrary positioning on top of that. I think this is something best served by a custom screen outside of this repo.

**Comment by admdikramr** [comment]
It's a single static ordering given by both the Rules of Flat Track Roller Derby and the WFTDA Officiating Cues, Codes, and Signals -- those are the same documents that specify what the letters are, and what the letters mean. So it's isomorphic with the letters we use in the first place, and is no more arbitrary.

**Comment by official-sounding** [comment]
Arbitrary meaning "not alphabetical" in this case. We get alphabetical sorting for free from both Java and JS, but to order it in WFTDA cue order, we'd have to pass that ordering information all over the place to ensure it showed up in that order.

Especially since CRG supports dynamic penalty code lists, it doesn't necessarily represent a single ordering, the ordering code has to be generic enough to support other formats.

I don't personally see enough of a usecase here to justify the outsized implementation and support costs.

**Comment by AdamSmasherDerby** [comment]
Also, I think subset of PTs who would find this ordering desirable is quite small.

**Comment by admdikramr** [comment]
I'll cycle back to this thread after Playoffs and see whether there is real demand for this from the people who are using it.

**Comment by JeneralPain** [comment]
Perhaps the layout could be changed but I think moving things around could be a problem... it's alphabetical order currently and I've personally no issue with it.
