### ISSUE TITLE
Feature Request: Audio (scrimmage/etc use case, low priority)

### ISSUE THREAD

**Issue by akeyes** [rollerderby/scoreboard#172]
I've tried to figure this out in the past, been told it would be easy, then got nowhere, so I'm posting here. Lowest of all priority obviously.

As the scoreboard can already start jams after 30 seconds (optional setting), end jams after 2 minutes, etc, I'd love to be able to add a few audio alerts at specific time points for use in scrimmages and other (non sanctioned) times of low NSO numbers.

- When Lineup clock = 25 seconds -> play audio clip "five seconds"
- When Lineup clock = 30 seconds (coupled with the setting to start the jam after 30 seconds of lineup, or when 'start jam' is pressed) -> play single whistle sound
- When a jam expires (2 minutes, or whatever it is set to) -> play 4 whistle audio clip

This would eliminate the need for a dedicated NSO to jam time (outside of the 5 seconds/start jam hand motion, hence scrimmage/fun games/etc, not a sanctioned game), while allowing NSOs present to cover more ground. This is obviously a very small scope of use cases, especially when coupled with the need for audio connected to the scoreboard system. Heck, I'd be happy if I just knew how to add it myself with a reference for others would might be interested as well.

**Comment by brian-brazil** [comment]
The WS API is documented at https://github.com/rollerderby/scoreboard/wiki/WebSocket-and-State, and you could use that in a custom program to trigger sounds.

**Comment by official-sounding** [comment]
I had actually been thinking about adding this -- Having a legitimate alternative to requiring a jam timer can pave the way to potentially making it optional and help staffing considerations.  That said, while conceptually it's pretty simple, but there are a lot of nuances that make it fairly complicated to implement:

1. What plays the sound? if it's the browser, is it the operator screen or the scoreboard? is it a dedicated browser window? is it the java server itself?  Should this be configurable?
2. If the browser plays sound, Chrome [has some upcoming changes to WebAudio](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes#webaudio) that will potentially make it harder to play sound without being hooked directly into user input.
3. Integrating this with our ruleset editor so that non-WFTDA whistle patterns can be played for different events (eg MADE starts a jam with a short whistle, but ends it with a single long whistle instead of 3 sets of 4 short)
4. Supporting all of the corner cases around whistles (eg coming into/out of a timeout, handling the rolling whistle at halftime)

Not all of these things are required in a scrimmage-type situation, but if I was implementing it, I would want to at least make it easy to cover these points, which makes it more of an undertaking than it seems on the surface.

Brian's suggestion is honestly probably the best one: make this an external program that listens for WS events, and trigger sounds/air horn/electronic whistle/etc based on that, rather than integrating it into the scoreboard directly.

**Comment by official-sounding** [comment]
there is now a (very limited subset) of this functionality in a separate program called [crg-jamtimer](https://github.com/official-sounding/crg-jamtimer)
