### ISSUE TITLE
Feature Request: Show retained official review on overlay

### ISSUE THREAD

**Issue by AdamSmasherDerby** [rollerderby/scoreboard#201]
Would be nice to be able to see on the feed if an official review has been retained or not taken, just like on the scoreboard.

**Comment by JeneralPain** [comment]
Hey Smasher,

Just had a look at this, sorry I've been a bit absent since I broke my wrist last year and then had my gall bladder out (because it felt left out).

Anyway... I've confirmed with the current head that when you "retain", it changes from "O" to "R" using the DDTV2017 interactive overlay.

[https://imgur.com/a/WV5aq9Z](url)

Is this what you mean?

Thanks

JP

**Comment by AdamSmasherDerby** [comment]
I'm referring to the WFTDA overlay, which is the only one most viewers ever see.
