### ISSUE TITLE
Update Java Dependencies

### ISSUE THREAD

**Issue by jaredquinn** [rollerderby/scoreboard#3]
The version of jetty used by CRG is way past EOL and no longer maintained, we should investigate the possibilities of updating to the latest jetty.

**Comment by official-sounding** [comment]
is there any interest in updating the build process to include Ivy, or overhauled to use something like gradle at the same time, so that the dependencies don't need to be embedded into the repo?   Understandable if that increases the scope of this too much, but might make it easier to keep up with dependencies in the future.

I'd be willing to take a look at this, in any case.

**Comment by jaredquinn** [comment]
I guess that depends on how long we stick with our current java core.

**Comment by jaredquinn** [comment]
Taking this back to the FB group for more discussion.

**Comment by brian-brazil** [comment]
One thing to watch with newer Jetty's is that it also requires a newer Java. While in theory everyone should have Java 8+, I'm not sure that's true in practice.
