### ISSUE TITLE
Designate a Star Pass on the scoreboard screen

### ISSUE THREAD

**Issue by docskinner** [rollerderby/scoreboard#398]
It would be nice to have a visual indicator on the scoreboard that a star pass has occurred for a particular team in that jam. This would allow the head official to easily confirm that the scoreboard has recorded the star pass, but more importantly would be a signal to the crowd who may be unclear about what happened. There are a variety of unicode star symbols (⋆☆⍟★☆✪✫✬✯⭐) or even a simple asterisk (*).

**Comment by brian-brazil** [comment]
Given the current scoreboard layout, we have unused space above the jam totals.

I'd not use below the clocks (may not be on projector screen), nor beside the clocks (bit tight).

We could also consider indicating lost and NI.

**Comment by frank-weinberg** [comment]
I'd rather put it on the line with the Jammer name, either on the outside below the timeout dots or in the middle below the jam points. (And I think outside would be better, as in the middle it's probably harder to spot which team had the SP.)

Moving the jam points up to align with the top of the total points boxes and putting the SP symbol below them might also be an option if we don't want to give up room for the Jammer name, but my gut feeling is that this would look odd, as most of the time the SP symbol would not be displayed.

> We could also consider indicating lost and NI.

While I'm generally in favor of giving people more information I'd say these are not important enough to give up screen space for them.
But thinking about it, we could maybe integrate the initial trip info with the Jam score, showing e.g. an "I" instead of a 0 while the Jammer is on their initial trip (and has not scored points) or marking the box in a different color (though this easily interferes with readability).
Without extra screen space, Lost would probably have to be a highlight different from Lead. It should not interfere with readability of the name and it should always be distinguishable from Lead. If it can be confused with no highlight at all in suboptimal lighting conditions, that's probably acceptable, so I'd look into using a light color for this.

**Comment by brian-brazil** [comment]
I don't think subtle colours will really work on this screen, as we need to be high-contrast given typical lighting in a venue. That red for no more jams makes the value unreadable isn't problem for example is because it's the lineup clock rather than the period clock that it's affecting, and the unreadable redness is the signal.

Similarly with lead: it's not very readable, but the flashing is the signal.

> in the middle below the jam points.

The jammer name is actually lined up with the clocks below currently. It looks like we've a bit of vertical space between the jammer name and scores to play with too (about half the height of the OR box). We could use all this to make the jammer name bigger, the longer names are already a bit difficult to read.

We could also move the clocks down a bit.

> an "I" instead of a 0

I is a bit close to 1, an X (per the NI's X) or blank might work. The main use I'd see is knowing if the jammer coming out of the box is still on their initial. Combined with lost you can also tell if lead is open.

Any additional UI elements here will make things more cluttered one way or the other.

**Comment by frank-weinberg** [comment]
> I don't think subtle colours will really work on this screen

The line of thought is basically: This would give the extra info to a subset of users while not degrading everybody else's experience. Since the info is quite unimportant, the latter part should be the main focus when/if integrating it.

> an X (per the NI's X) or blank might work

Blank is probably best - that's easy to identify at a glance.

**Comment by brian-brazil** [comment]
If it needs to be visible to certain people, it still needs to be visible. How relevant someone's use case is for this doesn't change whether the projector is washed out in a particular venue. That also assumes that the only people interested in this also have good eyesight.

Also if only a small subset of users want certain specific information but it doesn't matter to anyone else, that's what custom screens are for.

> Blank is probably best - that's easy to identify at a glance.

That might cause confusion for those expecting to see something in the box, and now wondering if there's a bug. I'd be tending towards the X if we're adding it.

**Comment by frank-weinberg** [comment]
> If it needs to be visible to certain people

The subset I'm talking about is not defined as "people that need it" - for a not too loose definition of 'need' that set is probably empty. It's "people that find it useful and happen to be watching a display on which they can make it out". 

> Also if only a small subset of users want certain specific information but it doesn't matter to anyone else, that's what custom screens are for.

If it can be included without degrading anyone else's experience, I don't see why it shouldn't be in the main release. We include an overlay despite only a small subset of CRG users streaming their games, similar for the full screen image or video display option. Heck, the whole stats tracking should be removed by that line of thinking, as it's only used by a small subset of users so far.

And may I remind you that you were the one who suggested to display Lost in the first place?

> That might cause confusion for those expecting to see something in the box

A '-' or '_' might be a compromise. Then the box is not empty but it's still relatively easy to distinguish from a number.

**Comment by brian-brazil** [comment]
> And may I remind you that you were the one who suggested to display Lost in the first place?

It's a suggestion, but if we have it on the main scoreboard it needs to be as visible to anyone who wishes to look for it as other elements on the scoreboard are. Otherwise we're unnecessarily discriminating against those with poor eyesight (the timeout indicators are already a bit problematic).

What are you currently proposing as the SP indication? As SP implies Lost, we could have both share the same position but with different symbols. Any potential SP indicator needs to be similarly visible to everyone.

> A '-' or '_' might be a compromise. Then the box is not empty but it's still relatively easy to distinguish from a number.

`-` would be the clearer of those two (though probably an en- or em-dash), why don't you like X?

**Comment by frank-weinberg** [comment]
> unnecessarily discriminating

By that measure, having a scoreboard at all is unnecessarily discriminating against blind people. The only options on the table right now are giving it to no one or giving it to some people after all.

But as indicated above, I'm totally fine with just not showing lost on the main scoreboard.

> As SP implies Lost

It doesn't. It only implies "not lead".

> why don't you like X?

Because it has the same dimensions as a digit and is thus harder to distinguish from one. For a JR who can only take a brief glance this can easily make or break the feature.

**Comment by brian-brazil** [comment]
> By that measure, having a scoreboard at all is unnecessarily discriminating against blind people. 

That's a strawman, which doesn't help us more forward.

What I'm arguing is that any new indicators need to be at as visible as existing indicators.

You never indicated what your current ideas were for the SP indicator, it's not quite clear from the above thread.

> It doesn't. It only implies "not lead".

True. To be more precise, if there's been a star pass there's no need to indicate lost, as there is no longer the opportunity to get lead.

> For a JR who can only take a brief glance this can easily make or break the feature.

That makes sense, though I've difficulty imagining it with our current fonts.

**Comment by frank-weinberg** [comment]
> What I'm arguing is that any new indicators need to be at as visible as existing indicators.

But your rationale does not support your point. Your rationale supports prefering equally visible indicators over less visible indicators but it does not support prefering less visible indicators over no indicators at all.

> You never indicated what your current ideas were for the SP indicator,

I'm not settled on this. As of now I'd look into some 5-pointed-star unicode char for a first try. Though I'm also wondering if there is a symbol that would be easily recognized as a pivot stripe and if so if that would be preferable.

**Comment by brian-brazil** [comment]
> it does not support prefering less visible indicators over no indicators at all.

My underlying argument is that any information on the scoreboard that may affect a teams decisions should be provided so everyone has an equal opportunity to avail of it as far as is practical. Knowing about a SP, Lost, or NI could all reasonably affect a team's tactics.

There's currently nowhere on the scoreboard screen where game information is indicated solely by a slight colour difference, which could provide an advantage/disadvantage based on things like colour blindness.

There's a threshold there where having a less visible indicator becomes game impacting depending on the exact genetic/medical makeup of the teams, so no indicator would be better.

As an example if we choose green and brown as two colours to distinguish something, that'd be unfair to those with red-green colour blindness. Given that is a condition which does not affect all groups equally, we'd be better not having that indicator in game terms.

Anything like that would also cause general accessibility issues for the audience, and we shouldn't be creating accessibility problems.

So let's stick with black and white; and if we have to flashing and (unreadable) red.

> I'm not settled on this. 

As one idea the letters `SP` could do the trick, and also avoids us running into any potential Unicode font variation fun across platforms. If it were above the jam total, that would work nicely I think. You might just about get away with `LOST` there too - if we want to indicate that.

**Comment by frank-weinberg** [comment]
> My underlying argument is that any information on the scoreboard that may affect a teams decisions should be provided so everyone has an equal opportunity to avail of it as far as is practical.

Ok, with that angle added the argument supports your point.

But then we should also consider that officials crews are not trained to reliably track lost status in real time. And if teams make a decision based on a wrong "lost"-indication we might have all sorts of debate. So from a fairness POV visibility might not be the biggest issue. I guess we should just leave it out.

>  the letters SP could do the trick above the jam total

That's probably be the most practical solution, though my sense of aesthetics is sitting on my shoulder crying "but, but, but..."

**Comment by brian-brazil** [comment]
> But then we should also consider that officials crews are not trained to reliably track lost status in real time.

For once, I'll be the one to argue that that depends on your crew - even just on paper :)

There's also less time sensitivity than say SPs (unless it's the initial trip, and they're trying to get out via a SP before the other team gets lead).

> And if teams make a decision based on a wrong "lost"-indication we might have all sorts of debate.

Scoreboard information is known to lag for more important stuff like points, I'm not too worried on this per-se. 

> I guess we should just leave it out.

Yeah, NI is probably more interesting generally. Plus all this is new, and of the new SK stats NI is a more important thing to try to focus operators on. Lost is much more niche.

> though my sense of aesthetics is sitting on my shoulder crying "but, but, but..."

Yeah, I've yet to come up with something that's much better. Could do a star or a stripe to the outside of the jammer name - there's some precedent for the star on overlays at least for lead jammer.

I'm also seeing now ways I can give the jammer names more space, or maybe make the timeout counts bigger.
