### ISSUE TITLE
[BUG] v 4.0.1 no more responds when uploading an image

### ISSUE THREAD

**Issue by tikismoke** [rollerderby/scoreboard#419]
Hi all,

found that CRG do no more answer when dropping an image in team logo.

I'm pretty sure it's due to the ' character in the image name.

The logo png is named "Track'ass Roller Derby de Tours.png"
If i removed it from the html/images/team path it all rework (after restarting the java apps).
Uploading it via the upload button and selecting path do the same.
The logo comes from a version 3.9.5 teams logo path and was working.
Removing the ' characters from the filename remove the issue.

Have a nice debug christmas holliday :)

**Comment by engineerlondon** [comment]
I have been able to re-create this, but not get a stack trace, the UI hangs, the application does not crash out:

Steps taken:
1. Start scoreboard ("Dev" branch) running in IDE (I used InteliJ) in Debug with --gui command line argument and a blank file in the folder: com/carolinarollergirls/scoreboard/version/release.properties
2. Navigate in the UI to "Scoreboard Operator Panel" supply a name eg: "test"
3. Navigate to "Up/Download" expect the "American Flag" + image
4. Using OS file explorer create a copy of the file scoreboard\html\images\fullscreen\American Flag.jpg in the same folder.
5. Rename the copy to "Track'ass Roller Derby de Tours.jpg"
Expected:
- Web UI to show a new file with Name="Track'ass Roller Derby de Tours" and image American flag, when viewing the "Up/Download" tab in a web browser (I used Firefox url "http://localhost:8000/nso/sbo/?operator=test") shows: "A web page is slowing down your browser, what would you like to do?" Stop it/ Wait. UI is unresponsive, re-loading "http://localhost:8000/nso/sbo/" is unresponsive, Java window ScoreBoard output window shows no new output.

- The issue requires more than just the quote mark in this file name, when I name the file "te'st.jpg" it loads fine.
- "Track'ass Derby.jpg" - is also fine
- The problem seems to be a combination of the quote and file name length: "testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttestte.jpg" - is fine
- but adding a single quote at the start causes the issue, eg: 'esttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttestte.jpg

I have tried to re-create the same using a unit test, simply a copy of "testFileCreation" with a different input file name in MediaImplTests class however it passes, when I was hoping it would fail:

` @Test
    public void testLongQuoteFileCreation() throws Exception {
        var fileName = "Track'ass Roller Derby de Tours.jpg";
        dir.newFile("html/images/teamlogo/" + fileName);
        ScoreBoardEvent e = collectedEvents.poll(1, TimeUnit.SECONDS);
        assertNotNull(e);
        assertEquals(BatchEvent.START, e.getProperty());
        e = collectedEvents.poll(1, TimeUnit.SECONDS);
        assertNotNull(e);
        assertEquals(MediaType.Child.FILE, e.getProperty());
        assertNotNull(media.getFormat("images").getType("teamlogo").getFile(fileName));
        e = collectedEvents.poll(1, TimeUnit.SECONDS);
        assertNotNull(e);
        assertEquals(BatchEvent.END, e.getProperty());
    }`

- Does this suggest it is a JS issue?
- Is there a way I can test that the API is serving a valid result to the JS?
- Any thoughts on what I should do to track this one down?
- Can I adjust the logging level? To get more detail?
- Is there developer getting started guidance I have missed?

**Comment by frank-weinberg** [comment]
> Does this suggest it is a JS issue?

Yes, all the symptoms point to a JS issue.

> Is there a way I can test that the API is serving a valid result to the JS?

You could check if the autosave JSON is well-formed - that's a dump of the same data tht is fed through the API.

> Any thoughts on what I should do to track this one down?

Does this also happen in Chrome? Is there any output on the Browser JS console?

> Can I adjust the logging level? To get more detail?

Only by adding additional log statements to the code.

> Is there developer getting started guidance I have missed?

No. Dev documentation is unfortunately still essentially nonexistant on this project.

**Comment by engineerlondon** [comment]
> You could check if the autosave JSON is well-formed - that's a dump of the same data tht is fed through the API.

I have checked that scoreboard\config\autosave\scoreboard-0-secs-ago.json is valid json by pasting into https://jsonformatter.org/json-parser, if i edit the json to be invalid the parser shows an error.

>Does this also happen in Chrome?

Yes, Google Chrome 79.0 (latest available) has the same issue. (and its not even possible to stop the offending tab without killing it using Task Manager).

> Is there any output on the Browser JS console?

Not that I think is relevant, when I trigger the error there is nothing written to the Browser Console, prior to adding the offending .jpg there is an error:
Cannot read property 'Effective' of null TypeError: Cannot read property 'Effective' of null
    at http://localhost:8000/components/rulesets-tab.js:210:22
    at Object.triggerCallback (json\WS.js:116:5)
    at Object.processUpdate (json\WS.js:140:8)
    at WebSocket.WS.socket.onmessage (json\WS.js:60:9)"
But I believe it to be unrelated since it appears before I have created the image that causes the JS to hang.

> Only by adding additional log statements to the code.

I have adding some extra Console out debug statements to the JS (scoreboard\html\components\data-management-tab.js) and I think I have reached the limit of my understanding as to what is going on with the JS.

Output with no quote mark in file name new log messages are produced:
Loading Scoreboard Media... data-management-tab.js:78:11
k.Format: imagesk.Type: fullscreen k.File: testesttesttesttesttest.jpg data-management-tab.js:80:11
searching for tr.Item[file="testesttesttesttesttest.jpg"] data-management-tab.js:83:11
Finished loading Scoreboard Media... testesttesttesttesttest.jpg data-management-tab.js:110:11
Loading Scoreboard Media... data-management-tab.js:78:11
k.Format: customk.Type: view k.File: example.html data-management-tab.js:80:11
searching for tr.Item[file="example.html"] data-management-tab.js:83:11
GEThttp://localhost:8000/images/fullscreen/testesttesttesttesttest.jpg [HTTP/1.1 200 OK 4ms]
Finished loading Scoreboard Media... example.html data-management-tab.js:110:11
GEThttp://localhost:8000/custom/view/example.html [HTTP/1.1 200 OK 3ms]
Loading Scoreboard Media... data-management-tab.js:78:11
k.Format: videosk.Type: fullscreen k.File: American Flag.webm data-management-tab.js:80:11
searching for tr.Item[file="American Flag.webm"] data-management-tab.js:83:11
Finished loading Scoreboard Media... American Flag.webm data-management-tab.js:110:11
Loading Scoreboard Media... data-management-tab.js:78:11
k.Format: imagesk.Type: fullscreen k.File: American Flag.jpg data-management-tab.js:80:11
searching for tr.Item[file="American Flag.jpg"] data-management-tab.js:83:11
Finished loading Scoreboard Media... American Flag.jpg data-management-tab.js:110:11
GEThttp://localhost:8000/images/fullscreen/American%20Flag.jpg [HTTP/1.1 200 OK 5ms]
Starting updateAllUrl. data-management-tab.js:236:12
Starting allDataA.attr. data-management-tab.js:242:12
Finished allDataA.attr. data-management-tab.js:244:12
Finished updateAllUrl. data-management-tab.js:245:12

... repeats every few seconds.

When the quote mark is added to the test file name:
Loading Scoreboard Media... data-management-tab.js:78:11
k.Format: customk.Type: view k.File: example.html data-management-tab.js:80:11
searching for tr.Item[file="example.html"] data-management-tab.js:83:11
Finished loading Scoreboard Media... example.html data-management-tab.js:110:11
GEThttp://localhost:8000/custom/view/example.html [HTTP/1.1 304 Not Modified 2ms]
Loading Scoreboard Media... data-management-tab.js:78:11
k.Format: imagesk.Type: fullscreen k.File: 'testesttesttesttesttest.jpg data-management-tab.js:80:11
searching for tr.Item[file="'testesttesttesttesttest.jpg"] data-management-tab.js:83:11
Finished loading Scoreboard Media... 'testesttesttesttesttest.jpg data-management-tab.js:110:11 

GEThttp://localhost:8000/images/fullscreen/'testesttesttesttesttest.jpg [HTTP/1.1 200 OK 4ms]
Then it hangs using ~25% of my CPU and we get no more messages, ie it does not move on to updateAllUrl.

The function that I think is responsible, is registered with the web socket provider: `WS.Register('ScoreBoard.Media.Format(*).Type(*).File(*).Name', function(k, v) { ...`
And I don't really understand what is happening at this point?
- I assume that the Java app detects the change and posts new data to the Json file, the scoreboard\html\json\WS.JS picks up on this change? And in turn calls the above registered function? which executes to completion.
- So I guess there is other registered JS gets called, and perhaps I haven't added logging to the right function?
- I note that if I add a single quote to the file name the file does not render(you get an image of a broken image path, ie it cannot find the file) so even once the issue has been identified, and resolved it will likely spawn a new defect for file paths that contain special chars.

I was wondering if an alternative, less elegant solution might be acceptable, could we strip the quote from the file path in the Java app before loading it?
Downsides that I can think of:
- Would require the file to be re-named without giving any warning to the person adding the file.
- The name in the UI will be missing the ' mark, although they can add it back in if required.

Alternatively, files with a quote could be ignored by adjusting the regex for valid files in the Java. Again its a bit of a sub optimal solution, but in this case a log message could be printed to the Java console.

When I have a little more time I will take a look at adding some debug messages to the other JS that looks relevant.

Many thanks in advance,
Tom.

**Comment by brian-brazil** [comment]
It sounds like we're not handling file names cleanly somewhere. We should fix that, rather than trying to workaround it. Among other things it may indicate a security issue if we've improper escaping.

**Comment by frank-weinberg** [comment]
I've traced the source of the bug. It's not in the Up/Download tab but in the Settings tab. Specifically in the listener that updates the dropdowns - `html/json/WSutils.js` line 20:

`select.children("[value='"+k.File+"']").remove();`

hangs when the offending file is being processed.

Seems to be a bug in jquery - we can either try to work around it or look into finally upgrading to a less ancient version.

**Comment by IWishICouldUseComputers** [comment]
@frank-weinberg agreed, I discovered the same about the time that I got your email (so glad to have the confirmation). I then went to reply and found I have locked myself out of my account with 2FA.
Anyway I tried simply adding `escape(k.File)` and it appears to solve the issue at first glance?
