### ISSUE TITLE
[FeatReq][LOW][LEGAL] Feature Request: Add pronouns field for skaters

### ISSUE THREAD

**Issue by goldenapples** [rollerderby/scoreboard#427]
Has there been any thought to adding a pronouns field for skaters that can be displayed on some views?

I've seen teams add pronouns to the skaters name in parentheses, but it would be nice to have them separate so they can be displayed smaller. Also, you might want to display pronouns on certain views but not others - for example, display on the overlay but not on the scoreboard itself.

**Comment by brian-brazil** [comment]
The only place we display skater names is on the scoreboard/overlay, and we're tight on space for those already. I'm not seeing how this is related to the scoreboard, it's not a general people management tool.

**Comment by AdamSmasherDerby** [comment]
When we have a more robust announcer infrastructure it might be helpful, but for the time being, all we are displaying is proper nouns.

**Comment by brian-brazil** [comment]
I did some light reading on GDPR last night, and I don't think this is a feature we should add for any audience-visible screen - even with the opt-in&warning on the overlay admin screen that Speedy and I had talked about. The short version is that there's a high chance that even with the best of intentions such a feature would result in someone being outed, which wouldn't be cool.

Derby as a community strongly supports expression of gender identify and that's something I think we as a community should continue to encourage for those who wish to do so. That's however different from indiscriminately broadcasting skaters' gender identity to the world.


Firstly it seems likely that such data would end up in the scoreboard without explicit or sufficient thought being given to it. I'd presume we'd aim to make it work so that you could copy&paste pronouns straight from Mothership and other sources like infopacks while you're copying over skater names&numbers (and presumably pronunciations/announcer notes at some point).

Secondly it doesn't seem unlikely that if we had an opt-in on the overlay admin page to show pronouns that, even with a tooltip warning you about the implications of enabling it, someone would with the best of intentions enable it without freely given, specific, informed and unambiguous consent from each individual skater. I've heard stories of a bench coach/captain indicating that all of a team is she/her, when that's not the case - it's not hard to imagine the same happening here with consent. Or a skater feeling they have to provide a pronoun via social pressure, even if they aren't comfortable sharing it - and either being outed or having an incorrect pronoun shown, both of which are undesirable. Or not providing it and having a conspicuous gap, which is also undesirable. Or a skater being told it's being used by the officials and/or announcers, but forgetting to mention that it'll be permanently and publicly online in video form.

I see a higher impact from a livestream overlay than announcer audio on a livestream. To figure out a skater's pronouns from a video currently you'd have to listen to ~90m of audio and hope that an announcer uses a skater's pronoun at some point, which is a fair bit of work for an adversary. If it's on the overlay all you'd need to do is look a few minutes before the game starts for when the roster is clearly displayed including all the pronouns right there on the screen. 



In GDPR terms (which is really just a particular way of saying in terms of the human right to privacy) and the caveat that I'm not a lawyer, I suspect pronouns would be a “special category” of personal data per Article 9 of the GDPR as it'd seem they'd fall under "Data concerning a natural person’s sex life or sexual orientation." For what we'd be using it for, my reading of Article 9 is that the only legal basis for having it in the scoreboard would be consent. There's also a duty of data minimisation, that is not to collect or keep personal data without a good clearly stated reason. Put another way, from a privacy standpoint it'd be best to not have to deal with a particular piece of personal data in the first place. As CRG Developers I don't believe we are data controllers here as this is on-premises software, but I think we still have an ethical duty to help our users not inadvertently violate human rights. The potential fines here are also enough to be the end of any derby league or governing body.

Once we have an announcer screen it may make sense to have pronouns (though it'll be a fair bit of work to keep them appropriately protected, e.g. we wouldn't want them ending up in a game JSON file, which was then publicly available on request as part of a statsbook for a sanctioned game), but I don't think we should offer the possibility of them being on an overlay or anything else audience visible.

If some tournament really wants to show them, and has done all the legwork of getting individual consent, and figured out their approach to handling when a skater requests that their pronoun be removed (are you just going to take down all videos of the tournament?), then having to produce their own custom screen or install an existing one is not much of an additional burden.
This seems far better to me than potentially handing all users of CRG a privacy and legal quagmire.

**Comment by goldenapples** [comment]
I'm not understanding the privacy concern here. It seems to me that pronouns are the **single most public** piece of identifying information... along with name _(edit: to clarify, I'm talking about **skater name** here, not legal name)_, which is already being displayed. What would an "adversary" do with an individual's pronouns, other than know how to refer to them appropriately? 

I think you may be overthinking this a lot - asking for pronouns doesn't have anything to do with orientation or sexuality, and should fall under the category of "manifestly made public by the data subject". There's a huge difference between sharing an inherently public piece of identification like pronouns and sharing something like legal name, which would be a clear privacy violation.

For context, this came up for me while watching WFTDA Champs. Quite a few times I saw skaters I wasn't familiar with and didn't know how to refer to, or how to pronounce their names, etc. Luckily most WFTDA teams include pronouns, short names, and pronunciation in their rosters, so I was able to look them up on wftda.com. I just thought it would be helpful to have that information accessible in overlays.

I don't have a clear idea of how the UX would work. I think there's a general architectural question of how to handle and display metadata beyond what's needed for keeping score. But I certainly don't think GDPR is a blocker.

**Comment by brian-brazil** [comment]
> It seems to me that pronouns are the single most public piece of identifying information... along with name,

Huh? Noone is generally under any obligation to tell everyone their legal name or other personal information. I suspect you may be overgeneralising the laws and practices in your jurisdiction to other legal jurisdictions.

> What would an "adversary" do with an individual's pronouns, other than know how to refer to them appropriately?

There's many places in the world where announcing that someone was trans or otherwise queer would not be good for their personal safety. Being able to see the history of a person's pronouns over time could be similarly problematic.

This is however irrelevant. As soon as someone who isn't meant to can get or gets the personal data, there's a problem.


I think this at the very least in the talk to a lawyer territory, and those aren't cheap.

**Comment by JeneralPain** [comment]
> For context, this came up for me while watching WFTDA Champs. Quite a few times I saw skaters I wasn't familiar with and didn't know how to refer to, or how to pronounce their names, etc.

Thinking about this as a gender diverse skater who constantly gets pronoun slapped in the general public. I understand and see the value, however, this is relying on the person entering the information into CRG being correct. And is effectively taking away effective management by the hosting league. For bouts where "need to know how to pronounce their names and/or gender markers", this should be in a packet that is being provided to the announcers. 

There is value in this, and I understand both brian-brazil's argument and yours goldenapples. 

> I just thought it would be helpful to have that information accessible in overlays.

It is helpful, however, I worry about it being used as a justification to skip proper bout management. When I run meetings as a HR for a game, I often seek clarification on any skaters that are disadvantaged by poor hearing [aka HOH - Hard of Hearing] skaters so that the referees can be aware of this and make appropriate adjustments to ensure the skater is aware of their penalty.

**Comment by JeneralPain** [comment]
> This is however irrelevant. As soon as someone who isn't meant to can get or gets the personal data, there's a problem.

Brian, we're not the "CIA" here, this information is often in documentation that I referred to in my prior comment that is supplied to commentators/event staff/first aid. I'm not as familiar with GPDR given I'm in Australia myself and pronouns aren't something I've dug into from the legal side.

I really think there is value in this suggestion but I don't see where we would place them. Because the audience generally only sees "Score and Time" on the main scoreboard. I don't see anywhere else that they might be "in the public eye" that would require their pronouns to be on display. 

Thinking about it, the only place pronouns would even be close to useful would be the penalty overlays/displays, but the penalty overlays are generally on the benches or the live stream. Where the commentator if properly briefed/provided team information.

And thinking more and more about my HR meetings as an example, I often make a clear point of referring to skaters as skaters. Even when I skate and I call an official review "I don't say 'she cut the track", I would make a clear point of "The Pink Jammer number 22 on Turn 3 stepped out when taken out of bounds by Blue blocker 93 and cut directly back in front of the blocker". That way there are no pronouns at all, there is no chance to upset them.

I guess brian also has a point of, what if the persons parents are watching the live stream but hadn't fully accepted the whole "Coming out", we could talk "what ifs" for ever in this thread.

My 10c
- There is value as an OPTION however, it's not a priority item in the list.
- It's a nice to have for those who WISH to use it but I don't see it having a huge uptake
- WFTDA have this in their "documentation" but pronouns do not form part of stats book or anything else.

**Comment by JeneralPain** [comment]
Whilst having "Pronouns" would be a positive for purely the announcers, and we don't have an announcers platform YET.

**Comment by bullseye555** [comment]
As #573 has introduced a Roster View, and there has been another request for this in the FB group, can we look to reopen this FR?

@JeneralPain @frank-weinberg?

**Comment by JeneralPain** [comment]
This requires this to be disclosed by skaters.It also takes up precious real estate.I have to ask, is it one person asking or is there weight to this one? Because whilst I get pronouns are important and I’m not saying they aren’t. Real estate on a small screen, plus the volume of use.If it will get used consistently and constantly then sure. But I fear we’re asking volunteer coders to make a significant change for one or two users and it’s not going to be a priority.Especially with a single report of a freeze that provided no data. So I’m just mindful of Franks effort level for reward. Sent from my iPhoneOn 15 Apr 2023, at 10:40 pm, bullseye555 ***@***.***> wrote:﻿
As #573 has introduced a Roster View, and there has been another request for this in the FB group, can we look to reopen this FR?
@JeneralPain @frank-weinberg?

**Comment by bullseye555** [comment]
Totally get that it's not something Frank my have the time to do. There's been half a dozen people so far support the idea (2 already in this thread, and 4 on the recent FB thread) - by no means overwhelming support

After a quick look at the Roster View, I feel there's sufficient room to include a pronouns field - and I think there's room in the Teams (skater management) page too

I too see a long-term benefit in including it but also acknowledge that it's a low level request, especially as the likely uptake on it would be slow (but I don't see that specifically as a reason NOT to do it) - I would be willing to work on making the changes so that Frank can dedicate time to other functional changes & bug fixes

**Comment by JeneralPain** [comment]
I'm going to reopen this one and leave it parked/low.

Need to investigate the GPDR as I have concerns that personal information and skaters would need to be told "that this could be displayed elsewhere". I know in Australia, the privacy principles apply here however, on review it looks like because we're not identifying the skater by FIRST or LAST NAME with their pronoun this is not considered personally identifiable. However, it is noted some teams use their last name for skater names, so this then becomes problematic.

As a community based system, we have to be careful because if we start tripping GPDR and other things, then it becomes a legal minefield we simply do not have ANY MONEY for whatsoever.

Considering the WFTDA pulled their online certification tool for generating a fresh "officiating resume" due to GPDR concerns raised, I have to take this carefully.

**Comment by frank-weinberg** [comment]
Since
1) we now have a roster screen aimed at use by announcers
2) WFTDA now has a public charter directory that includes pronouns (and legal names) 
I think the time has come to include pronouns in CRG. Given that this is straightforward to implement, I'll put this on the list for v2023.
