### ISSUE TITLE
Multiple Time Outs

### ISSUE THREAD

**Issue by SticksandStoner** [rollerderby/scoreboard#456]
Having fully read the documentation I would like to suggest a change to the default settings relating to time outs. Currently, if you stop a timeout, it goes into lineup by default which isn't in line with the approach taken in the majority of tournament procedures. 

Could we therefore change the default setting to recognise that pressing the "end" timeout button, ends the timeout/OR/whatever, but keeps the clock in timeout until a jam starts?

This would also prevent the issue which I have seen multiple times in the last few weeks whereby Team A takes a timeout, immediately followed by Team B taking a timeout. Because procedures state that operators should not go into lineup at the end of a timeout, the operator is simply "switching" the timeout to Team B. This means that Team A's timeout does not register.

**Comment by frank-weinberg** [comment]
Which clock is shown after the end of a timeout should not be the SBOs concern. The SBO should always press "End Timeout" at the rolling whistle. Whoever sets up the scoreboard for an event should set the setting to whatever the event in question wants to display. (The setting persists "Start New Game" so it only has to be done once.)

And the correct way to handle back to back timeouts without lineup time between them is to press "New Timeout" to start the second one.

(Given that the rules explicitly say that a timeout ends at the rolling whistle, I consider it wrong to display "Timeout" after that. And I refuse to make wrong behaviour the default.)

**Comment by ghost** [comment]
Tournament procedures state that you do not return to lineup and remain in timeout until the next jam start

**Comment by ghost** [comment]
"When coming out of a Timeout, the scoreboard should allow the timeout clock to
continue to run and go right from the timeout clock into the next jam starting."

As per 2019 Tournament Officiating Roles, Responsibilities, and Procedures

**Comment by frank-weinberg** [comment]
And that document then continues to give a reason for the requirement: "this is a limitation of the CRG software" meaning obviously the version used at the 2019 post season which is based on 3.9.1 according to said document.

**Comment by ghost** [comment]
But it is still the procedure gold standard.

Anyway, we're arguing over something subjective and down to personal preference, as there has yet to be any alteration in official procedures.

**Comment by frank-weinberg** [comment]
> But it is still the procedure gold standard.

It is a non-public document written for one set of tournaments and their specific constraints. Just because those are the highest level events in our sport doesn't mean we should blindly apply it in situations where the constraints are different.

**Comment by riffreff** [comment]
> Tournament procedures state that you do not return to lineup and remain in timeout until the next jam start

This procedure originates from the playoff season 2017, when going into lineup caused the WFTDA streaming overlay to sometimes display the timout flag incorrectly. This procedure may then have been copied and pasted into 2018 and 2019 guidelines. it is no longer up to date and should be abandoned (and probably will be in 2020).

The "gold" standard of WFTDA playoffs is out of date here because it refers to an older version of the software. We can't be backwards compatible with everything.

**Comment by SticksandStoner** [comment]
"When coming out of a Timeout, the scoreboard should allow the timeout
clock to continue to run and go right from the timeout clock into the next
jam starting. Please expect the Jam Timer to start the next jam at either
30 seconds after the timeout or when
both teams are ready, whichever is first."

This is from the 2019 postseason procedures. Yes, it does also refer to CRG
limitations, but given that most THNSOs are *not* particularly SBO focused,
they're likely to continue working to these standards until such time as
someone explicitly tells them otherwise.

**Comment by JeneralPain** [comment]
And the reason for going into line up was the overwhelming requests from Europe where they do it as

Time out > line up > jam start

Rest of world: time out > ends > extra 30sec counted > jam start

**Comment by frank-weinberg** [comment]
> they're likely to continue working to these standards until such time as someone explicitly tells them otherwise.

The CRG 4 instructions say that the (only) correct way to operate CRG 4 is to press "End Timeout" at the rolling whistle. This is because we are tracking timeout durations (which in the case of ORs are part of the paperwork).

Asking an SBO to do otherwise because last year's post season instructions that were written for a  completely diffferent version say so is like asking a JR in 2019 to count jammer lap points because the 2018 post season instructions said so.

And, again, for those that want the timeout clock to continue to be shown because they believe that this is better for the people looking at the scorebaord, there is a setting that they can set ahead of the event.
