### ISSUE TITLE
CRG Appears To Have Dependencies That User Log4J

### ISSUE THREAD

**Issue by JohnMarzulli** [rollerderby/scoreboard#489]
A quick scan of CRG shows that it appears that there are some 2nd level dependencies on Log4J.

This implies that there is a security risk when using CRG Scoreboard while connected to a network.

![image](https://user-images.githubusercontent.com/23081324/145756849-de178d5e-7502-49c4-90f2-3978b45efd37.png)

**Comment by JeneralPain** [comment]
Thanks John, I’ll raise this with the devs.

**Comment by frank-weinberg** [comment]
As far as I can tell from the screenshot and from looking through the jar-files in the repo, these are not instances of log4j but just interface classes that allow the respective component to use log4j if it is otherwise included. So it seems to me that we are not affected by the vulnerability.

If anybody has any indication that I missed/misjudged something, please let me know.

**Comment by frank-weinberg** [comment]
After reading up some more and having another look through the files bundled with CRG, I'm now completely confident that the current release of CRG does not include log4j either directly or indirectly and is thus not affected by the vulnerabilities in that library. (And I would be very surprised if that was different for any prior release, but I did not check those explicitly.)

Given that this issue has now been linked from the public Facebook group, I flagged it as invalid in order to make the message as clear as possible that CRG is not affected. The flag is not meant to imply criticism for opening the issue @JohnMarzulli. Actually, I am thankful you did do so in order to have it properly reviewed.

**Comment by frank-weinberg** [comment]
Addendum: I've come across the tool [log4shelldetect](https://github.com/1lann/log4shelldetect) that scans for vulnerable programs and ran it on all CRG releases I could get hold of. (That includes all releases available for download here.) It found them all to be ok:

![Screenshot_20211215_223937](https://user-images.githubusercontent.com/34135287/146269081-80205ca7-543f-4544-b7f3-5e32af0514a3.png)
