### ISSUE TITLE
ScoreBoard.CurrentGame.TimeoutOwner Giving invalid value

### ISSUE THREAD

**Issue by AdamSmasherDerby** [rollerderby/scoreboard#513]
5.04 / Windows / Chrome

I can't figure out what is getting me into this situation:

```
>WS.state['ScoreBoard.CurrentGame.TimeoutOwner']

>3cd5da7c-872e-446b-ab7c-411c69b025bb_1
```
This appears to be some kind of UUID, but I don't know what it's for.   The API says this should just be "1", "2" or "O". Changing the owner of the current timeout does not fix the problem.  Is there a different channel I should be looking at, or is this a bug?

**Comment by frank-weinberg** [comment]
That's a bug in the documentation. For TTO or OR these are references to a team and references always use long IDs. In prior versions long and short team ID were identical just "1" or "2". But now long IDs are "gameId_1" and "gameId_2" as they have to be unique across all data. You can just discard everything but the last character in order to get the old value.

I did try to use short IDs for this specific case as they would be much more convenient in the frontend but couldn't get that to work with any reasonable effort.

**Comment by frank-weinberg** [comment]
Closing as the Wiki has been updated following my previous comment.
