### ISSUE TITLE
[Potential Custom] Opening "Penalty Whiteboard Display" references specific link versus wide link

### ISSUE THREAD

**Issue by JeneralPain** [rollerderby/scoreboard#514]
When you open a penalty whiteboard, it opens it with ?game=<uuid> unlike the scoreboard which is just /views/standard

This breaks using Pi or other controller software that we will need constantly keep updating the =uuid for every game.

Can we get this switched/fixed back to /nso/pt/wb pls and thank you?

**Comment by frank-weinberg** [comment]
If the ID given is not the ID of the current game the JS will automatically trigger a reload with the ID updated. It will do the same if the current game changes while the screen is loaded. So just loading it with any ID should give you the desired result. (It doesn't even have to be an ID of an actual game, simply using "1" is enough.) Using the current ID on initial load just skips the immediate reload.

Or do I misunderstand what you are trying to do with your Pi?

Addendum: Even using `/views/wb/?` without any gameId works. (But it doesn't work without the ? at the end.)

**Comment by JeneralPain** [comment]
When you do anything else, it says “click for current game” but using pi signage it just pulls the webpage effectively.

And then it errors out with a jetty error

**Comment by frank-weinberg** [comment]
This is the first time I even heard of pi signage. From what I could gather with a quick search (I'm at a tournament this weekend and have little time) it sounds like it is either working as a browser or wrapping around one. And from your vague error description it sounds like it is inhibiting the refresh with changed gameId. If so there are 2 possibilities:

1. Pi signage can be configured to allow/do these refreshes. If so this is a configuration problem on your end.
2. Pi signage can't be configured in this way.
  - If pi signage is supposed to be used with dynamic pages I'd consider that a missing feature on their end.
  - If pi signage is only intended for static pages you're using it outside of it's specification.

So this definitely is not a CRG bug. Assuming this is a limitation of pi signage that will not go away we can treat it as a feature request to work around this limitation. I can see two ways of doing this:

- Completely redo how we handle gameIds. This would have to be done across all screens that use them and thus be a lot of work with a significant risk of introducing bugs. I'm not going to do that for such a niche feature.
- Make a copy of the relevant parts, switch them over to us `CurrentGame`instead of `Game(gameId)`, and use those for the WB screen instead of reusing the PT screen. That would create a maintenance burden to maintain essentially a second copy of the same code and we have decided we don't want to do this in the main CRG distribution. This is a scenario for a custom screen. Especially given that it's a niche use case.

**Comment by JeneralPain** [comment]
Lowering whilst I do a further deep dive and review, removing 'bug' tag.
