### ISSUE TITLE
[FEATURE REQUEST] Derby Scoreboard Control "Lite" Edition/Screen

### ISSUE THREAD

**Issue by JeneralPain** [rollerderby/scoreboard#516]
Hello,

I've had some feedback after TGSS this weekend in Adelaide that has come from many SBOs and the like. Whilst they all agree the advanced scoreboard screen we have now is valuable, strong and works. It's really for a very "small subset" of tournaments that use the full power of the scoreboard (this is often due to the financial, training and other restrictions on teams). 

What they have all universally asked for is:
- Very generic / basic scoreboard operator screen that is perfect for the "Home Game" or "Scrimmage with a scoreboard".

So fixing things is simple and easy, starting/stopping clocks is very simple, scoring is very simple. 

Don't get them wrong, they want to keep the "full fat" version of CRG because it has its place in the higher level tournaments (aka TGSS, Champs, Playoffs, etc etc) but it doesn't work as effectively for "a simple scrimmage" or home game. Which makes training new SBOs difficult as they get "scared off" by the options and screens.

Cheers

JP

**Comment by frank-weinberg** [comment]
- Why is using 3.9.5 not an option for those people/situations?
- Are they even in agreement what exactly should and should not be part of this basic screen?
- How do they expect transitioning from the simple to the full interface will work in practice? Can we get WFTDA on board to properly track experienced with simple vs. full interface in CVs?

And how many of those people have themselves started SBOing on 4.x (or 5.x)? So far I have only ever heard this request from people who started on 3.x and had to make the transition while people who started out on the new interface are perfectly fine with it. (And I didn't notice an increase in people who didn't want to learn SBO.)

**Comment by keleighshepherd** [comment]
I spent yesterday teaching brand new officials at a bootcamp, everyone who used CRG found it overwhelming - it does too much for most mom-and-pop leagues and officials. "just use an older version" is not really what I want to be teaching people. 

CRG is already terrifying to your average NSO, and to quote someone yesterday "its intimidating, I don't care about ePLT, or live statsbooks. I just want a scoreboard. I wouldn't think to use an older version because I'm not someone who is technical, but I can run scoreboard for my league"

Edited to add: A lot of these inexperienced officials have had no exposure of CRG pre-4.0

Also, its *PERFECT* for when you have me and other games data managers for major tournament play, but you shouldn't need me to take care of the tech for normal double headers

**Comment by frank-weinberg** [comment]
>  "just use an older version" is not really what I want to be teaching people.

Instead someone should put in a huge amount of work in order to create and maintain an interface that will give people all the same pros and cons that using the older version would give (plus probably some new bugs on top initially) with the only exception being it's not "old"?

Good luck finding that someone.

And BTW: Just to remind everybody of that interface that was so much simpler and less terrifying, here's a screenshot of the 3.9.5 vs. 5.0.4 operator screens next to each other. (Both from freshly unzipped installations.)

![Screenshot_20220619_215513](https://user-images.githubusercontent.com/34135287/174498213-d7ff6fa9-3e03-44e5-9e45-e2b21d62421c.png)
![Screenshot_20220619_215850](https://user-images.githubusercontent.com/34135287/174498295-276d1b16-203d-4b0d-b6fa-83c75fbba7b9.png)

I honestly don't see how either of these interfaces is less intimidating than the other one unless you happen to be already familiar with one but not the other.

Maybe even older? The oldest version I have a zip of is 3.0.0:
![Screenshot_20220619_221010](https://user-images.githubusercontent.com/34135287/174498844-8965512b-7762-4b0d-8957-bf720332ab10.png)

No clear improvement either, I'd say. (WTF are those 4 Jammer dropdowns per team doing?)

And some numbers because I was curious:

3.0.0: 83 input elements: 5 tabs, 65 buttons, 8 dropdowns, 5 text fields / 18 values displayed
3.9.5: 79 input elements: 4 tabs, 71 buttons, 4 dropdowns / 18 values displayed
5.0.4: 75 input elements: 6 tabs, 69 buttons / 20 values displayed

So according to the numbers interface complexity actually has a slight downward trend.

**Comment by atkinsonm** [comment]
One idea that could make the scoreboard feel less intimidating but preserve all functionality: what if the lineup, timeout, and intermission elements could occupy the same space and be swapped based on the game state? (show timeouts during timeouts, intermission during pre/post-game and between periods, and lineup otherwise). My perspective is limited to WFTDA but I don't personally see a circumstance in which having all of those displayed at the same time has a benefit, but maybe someone does.

**Comment by bullseye555** [comment]
I don't mind @atkinsonm 's idea - but I think having a single element may reduce functionality [you'd need at the minimum the Period and Jam clock, where Period = Period & Intermission, and Jam = Jam/Lineup/Timeout] and clutter the screen more (how else do you remove a Jam if you've only got one clock which is currently in Timeout - you've have to have a _Number of Jams_ field, and a _Number of Time Outs_ at a minimum), so I don't think we do _anything_ with the clocks

How about a _Simple Mode_ button (similar to the **Show Start/Stop Buttons**), where all it does is hides the functions that they may not want to use?
I figure a scrimmage is probably not going to worry about the following from the scoreboard
- Star Passes 
- Lead/Lost/Call/Injury
- Who the Jammer is
- Who the Pivot is
- The Score Sheet

![image](https://user-images.githubusercontent.com/28804763/218389865-08bd5cee-c45f-423b-af1e-95580eccec2c.png)

Or it's a popup box when clicking that button that allows the operator to hide certain elements? EG: They have a tick-box list that chooses to hide the above lines

**Comment by atkinsonm** [comment]
> how else do you remove a jam if you only have one clock

I go to the score sheet at the bottom of the operator panel and delete it from there. For timeouts I click the un- timeout button.

Someone on FB said that the best time to train on the scoreboard is during practices and scrimmages. I agree with that. I think a "scrimmage mode" would take away a training opportunity. Also, there's a certain simplicity in having one version of the operator panel. Having multiple may add more problems than it solves, maintainability being one and more conditions/settings being another. For those reasons, I recommend against having more than one version of the operator panel, but am not opposed to optimizing that view or adding other usability improvements like #405.

Just my two cents.

**Comment by bullseye555** [comment]
Yeah, I don't disagree about the training - but that wasn't the purpose of the initial request.

What was requested by those @JeneralPain and I were talking to was a simpler interface to use when you're just throwing someone at Scoreboard the first time so the don't seem overwhelmed. 

Eg: Click "Start", Click "Add Points", Click "Stop". Repeat until the game is done. If they're then interested in continuing doing scoreboard, we can start the training. I've personally seen users that get flustered by the amount of work they have to do, rather than easing into it, and say to me they never want to do scoreboard again. Having the simpler interface will remove some of that "scariness" from their initial experience, then we can gradually introduce complexity as they get more experienced

**Comment by WishboneBreaker** [comment]
I wanted to add the feedback I gathered last week at the Miami Valley OPE!n in Dayton OH. We had the pleasure of welcoming I believe 13 people with post-season WFTDA experience as NSOs.

If there is a simple/lite version made, my summary suggestion is to include all the functions/displays that are REQUIRED by the rules and as little additional functionality as feasible. Score up/down. Timeouts remaining. If the types of timeouts are displayed, then reassigning those timeouts if needed. Lineup clock. Game clock. Jam clock. Start/stop. Undo for all of the above. Undo last button pressed. Ability to change game clock manually during a time out. No need during an active jam to use the mouse. Actually, if the entire game could be run without the mouse, that'd be even better. As few as possible of things take "focus" from the operator screen, so a single hotkey press can start/stop current game state no matter what and popups or edit windows don't interfere with that ability.

**Comment by frank-weinberg** [comment]
From the screenshot above, https://github.com/rollerderby/scoreboard/releases/tag/v3.0.0 appears to be pretty close to that.

**Comment by WishboneBreaker** [comment]
I'll download that one and assess/compare, and then give my thoughts based on feedback I've heard from people.

**Comment by WishboneBreaker** [comment]
I took a look at 3.0, and I considered the input I'd personally received. There's a few oddities of this 3.0 release (and I'd have to refresh myself on some of the best practices we used to have), but for now I will go ahead and recommend people try this as a jumping off point perhaps for people wanting to run scrimmage or a game, but they don't have anyone experienced. I don't see anything specific that makes it unsuitable to run a game in 2023. 

If this ended up being a starting point for a future "lite scoreboard," there's probably many features we could strip from it. And there's probably additional features to ease use that could be added with the assumption that the user will be a new person. 

Or, if a "lite operator view" is made for the current development version, this is a pretty good example of the functions people would want to have still available, as well as the ease/simplicity of adding or subtracting points/timeouts.
