### ISSUE TITLE
Linux installation Error: Unable to access jarfile lib/crg-scoreboard.jar

### ISSUE THREAD

**Issue by PeetThesing** [rollerderby/scoreboard#519]
Hi,
while running the shell-file this error appears. The file does not exist.
Anyone any solution?
Kind regards and thanks for your work
Peetrasilie

**Comment by frank-weinberg** [comment]
There are two common reasons for this error:

1. You have the source code instead of the compiled application. You should have [crg-scoreboard_v5.0.4.zip](https://github.com/rollerderby/scoreboard/releases/download/v5.0.4/crg-scoreboard_v5.0.4.zip) for the current version. (In general the name of archives with the compiled application will start with "crg-scoreboard".)
2. You are trying to run CRG from the packed archive. You need to extract the archive in order to run CRG.

Is it either of those?

**Comment by PeetThesing** [comment]
Thanks, I downloaded the tar.gy Code-File, with the zip-file this Error is solved.
