### ISSUE TITLE
[FEATURE REQUEST] - PT/LT/PLT Page enhancements

### ISSUE THREAD

**Issue by bullseye555** [rollerderby/scoreboard#550]
When opening the PT/LT/PLT page, have a "Login" screen (same as SBO screen) that will:

1. Check if the name entered has been assigned a team in the IGRF and automatically open the PT/LT/PLT page for the assigned team
   -- EG: Based on the below (where VRDL/KCR is Team 1, and EVRD is Team 2)
![image](https://user-images.githubusercontent.com/28804763/202407123-fc948e43-8a7d-46f7-b7a4-64b16f7d1e95.png)
  a. Melon Head would automatically have _/nso/lt/?zoomable=x&team=**1**&game=xxx_ loaded
  b. Scare Bear would automatically have _/nso/lt/?zoomable=x&team=**2**&game=xxx_ loaded
  c. Officials names check should be case insensitive (eg: Melon Head == melon head == Melon head != melonhead)
  d. Do not allow progression past this screen if the input text is NULL or only spaces
  e. Pinch Zoom option should be selectable on this screen
2. If no name matches (or no entry in the NSO section of IGRF), or there is a name match but no team entered then progress to the existing _Option Editor_
![image](https://user-images.githubusercontent.com/28804763/202408059-e4c00e8d-391a-4202-8b07-03016adbccab.png)
3. The operator name would then either be displayed above the PT/LT/PLT screen (same as SBO) or within the area where the Team Colour is displayed
![image](https://user-images.githubusercontent.com/28804763/202415854-92270cbe-bcc5-4040-bf46-2bdfb9d44cd4.png)
or (suggested layout - Team, Left Aligned ; Operator, Right Aligned)
![image](https://user-images.githubusercontent.com/28804763/202416234-e79e5bdf-72d7-4dc9-a4f6-3317fb443840.png)

Stretch enhancement: If there is no team entered, or no entry in the IGRF for the official name entered, populate the relevant sections of the IGRF

**Comment by frank-weinberg** [comment]
I see a number of problems with this:
- Mandatory name entry is too restrictive - even on the operator screen it can be skipped.
- Having to click through multiple settings dialogs before you can start using the screen is bad UX.
- Typing in a name on the tablet is notably more effort than assigning teams in the IGRF tab.
- This would only work if the screen is newly opened for each game. "Go To Next Game" or a bookmark that includes `team=i` would skip it. So the IGRF tab would still have to be checked before exporting, further reducing usefulness.
- Forcing a team assignment entered ahead of time does not reflect the usual workflow in my neck of the woods, where (P)LTs decide themselves who does which team.

I would at most add the possibility to select/add a name in the existing options dialog.

**Comment by bullseye555** [comment]
Thanks for the feedback, Frank. I expected there may be some limitations, so this was always a 'best case' scenario

I'd be happy to go with having the ability to select/add in the existing dialog

**Comment by frank-weinberg** [comment]
Note that this is a low priority item on my list. So it may be a while until it's done.

**Comment by bullseye555** [comment]
Yeah, wasn't expecting this to be an overnight change.

Thanks Frank

**Comment by atkinsonm** [comment]
I think the idea has good intentions, but might actually make PT/LT/PLT more difficult instead of easier. Selecting the team and saving is a 1-2 button action, whereas entering a name involves typing a variable number of characters. It would also introduce a need to access a device's keyboard; no other functions of PT/LT/PLT currently use the keyboard. Most electronic PT/LT/PLT uses mobile devices and "virtual" keyboards that the software needs to open and can occasionally be disruptive to other content on the screen.

For comparison, the operator login serves a function beyond just getting to the right screen: saving key bindings. An SBO also more likely than not has access to a physical keyboard that they already use for other actions. I think for PT/LT/PLT login to be worth the extra steps/requirements, it needs to serve a purpose beyond what NSOs can already do with the team select.

**Comment by bullseye555** [comment]
@atkinsonm
Most of what you've commented on there was already raised by Frank - and the compromise was a Select or Add option in the existing popup.
This way, the user can select their name from a drop down, or optionally enter it

I think the _biggest_ roadblock is how to make sure a change of operator when changing game is handled as I can see a scenario where Game 1 has Operator A, then game 2 is supposed to be B, but is updated to A in CRG because there's no new dialogue to get the updated operator...

As a different option, could the operator drop down/text box be part of the actual PT/LT/PLT screen, and when it goes to new game, it reverts to Null?

**Comment by atkinsonm** [comment]
What you're describing sounds technically possible. I'm just trying to understand _why_ a PT/LT/PLT would want to enter or select their name instead of selecting a team. Would there be any benefit other than bringing them to the right team's screen, assuming that assignment was entered ahead of time and didn't change?

**Comment by frank-weinberg** [comment]
The assignment of operators to teams is used for filling out the headers of the statsbook on export. So if an operator sets both the team they track and their name, this doesn't have to be done on the IGRF tab before export.

But this is relatively little gain for quite a bit of headache regarding how to best do it.

**Comment by bullseye555** [comment]
Based on current discussion - happy to close this as not planned

As per @frank-weinberg - high effort for low gain

**Comment by atkinsonm** [comment]
I've never completed an IGRF individually, so I had an inkling that operator to team assignment might exist but I wasn't sure. This feature would make some sense for that purpose. Thanks for the context!
