### ISSUE TITLE
ScoreBoard JSON standardisation / versioning

### ISSUE THREAD

**Issue by aoanla** [rollerderby/scoreboard#557]
So, I _know_ that the scoreboard's JSON format is not strictly intended for consumption outside of the scoreboard itself... but there's also a number of things which are now depending informally on being able to parse it (not just wxproxy stuff, but also automatic score-incrementers-for-referees, a newly developing stats tool here: https://github.com/dhmay/jamstats and so on).

I know this conversation has been had before - and I don't seriously expect the crg JSON to change significantly! - but this is just to make a trackable note of this informal dependency.

[On a _personal_ note, the scoreboard JSON is a more useful and more information dense game record than the WFTDA statsbook, so I'd hope that anything doing serious work would parse it anyway, especially as xls is a much finickier thing to parse.]

**Comment by frank-weinberg** [comment]
Between getting the new WFTDA rankings ready for release and restarting Bundesliga I'm currently super busy and CRG stuff is on the back burner for a while. But i can give a quick acknownledgement and pointers for your ongoing discussion on FB.

First, I am very aware that there is a growing set of third party code and I am thus trying to avoid breaking changes in the WS API whenever possible. The main reason 5.0 was a new major version was the fact that I had to do significant breaking changes in the WS.

I will continue to maintain https://github.com/rollerderby/scoreboard/wiki/WebSocket-Channels to document not only the current but also all prior revisions of the API. (And your assumption that the files contain the same data as the live WS is essentially correct. There is only some auth credentials filtered out.)

Regarding the stats tool: I started working on the full game data support back when I was doing bench stats and my goal was to get stats including time to lead/ time out of initial. The statsbook support was only an intermediate goal.
I have long since stopped doing bench and correspondingly my priorities shifted but this is still on my list of things I'd like to include one day. So I'm excited to see it being actively worked on.
The times until end of initial (which is time to lead for the team that got lead) are of course stored. From memory, they should be in ScoreBoard.Game(<id>).Period(<num>).Jam(<num>).TeamJam(<id>).ScoringTrip(1).Duration

**Comment by aoanla** [comment]
Hi, thanks for the reply - and, indeed, this issue is a "tracking issue" rather than anything else (I just felt it needed to be stated somewhere for the record), so this reply is already more than enough!

**Comment by dhmay** [comment]
Thanks for the link to [jamstats](https://github.com/dhmay/jamstats), @aoanla ! @frank-weinberg , I've put an initial feverish burst of effort into jamstats and am now slowing down and thinking about growing usage and building features that people will use. 

I'd love to get feature requests from folks with an interest in doing stats-like things with CRG json files. If you have any ideas, feel free to reach out, by tagging me here or dropping issues into jamstats! I've got a violinplot of time-to-lead, but I could also add time-to-initial or different visualizations.

The thing I'd **really** love to do is set up live plot-making and -sharing for in-progress derby games.... maybe automate Facebook/Twitter/whatever posting of game status? But I have no familiarity at all with connecting to CRG live (I've only dealt with the JSON as files) and would need some help understanding that side of things.

**Comment by aoanla** [comment]
Hi, as I promised on the Facebook thread, I *will* submit you a pull request with some websocket stuff for connecting to a CRG scoreboard. 
Some notes on how this works to save Speedy time though:

1) when you register to the server to receive updates, you can state *which bits* of the game data hierarchy you want updates on. (So, say, you can register ScoreBoard.Team(1) for updates, and you'll only get updates that are within ScoreBoard.Team(1).*  )

2) updates are *incremental* - which I think probably needs the biggest changes in your parsing stuff. The *first* response from the server gives the "entire JSON" state currently. Each subsequent response is the difference between the previous state and the new state (so, say, every time the Score changes in a jam you get an update containing the Score element, and the new score). 

When I did some very basic playing around with stats like this years ago (https://github.com/aoanla/rdsb-ps was my attempt in badly written Go) I just regenerated all of the plots each time I got new info - but I also kept a datastructure that was very similar to the JSON, so that just needed trivial updates.
There's obviously better ways of doing incremental stats updates than this!

**Comment by dhmay** [comment]
In some sense I'm sure there's a more efficient way of doing incremental updates than that, but that's the way I'd plan to handle it, too. It's super fast to re-parse everything and remake all the dataframes. Generating the plots themselves is the slow-ish part.
