### ISSUE TITLE
Feature request: team roster import from spreadsheet

### ISSUE THREAD

**Issue by atkinsonm** [rollerderby/scoreboard#566]
As a scoreboard operator, I would like to import a team roster from a spreadsheet (e.g. CSV) so that I can easily import information that non-technical users compile without having to copy/paste fields myself.

Proposed fields: number, name, position. Skip any positions that don't match a known one (Skater, Non-skater, Bench Staff, etc.)

Acceptance criteria:
- import a spreadsheet into a team roster for a game
- keep existing team sync toggle behavior
- update (overwrite) existing values matching skater name, number, or position, if matching based on a present order of preference (exact name match, the exact number match would be suitable to me)

Export to CSV would be a bonus

**Comment by JeneralPain** [comment]
Hello NSO friend,The scoreboard already has full support for importing from the IGRF documentation.Is this not a sufficient amount of importing?Just want to understand the request in full so that we can triage it accordingly and give it the right order and attention. Cheers Sent from my iPhoneOn 2 Feb 2023, at 1:12 pm, Michael Atkinson ***@***.***> wrote:﻿
As a scoreboard operator, I would like to import a team roster from a spreadsheet (e.g. CSV) so that I can easily import information that non-technical users compile without having to copy/paste fields myself.
Acceptance criteria:

import a spreadsheet into a team roster for a game
keep existing team sync toggle behavior
update (overwrite) existing values matching skater name, number, or position, if matching based on a present order of preference (exact name match, the exact number match would be suitable to me)

**Comment by atkinsonm** [comment]
Hi @JeneralPain

The IGRF screen has buttons which allow me to _download_ a statsbook or JSON of game data. What I'm looking to do is _upload_ a team roster so the scoreboard automatically imports skater names, numbers, and flags. Is that an available feature?

Or are you suggesting that I pre-populate the "blank" statsbook with team rosters and CRG will import from there?

**Comment by bullseye555** [comment]
HI @atkinsonm - The instructions on how to import a pre-populated IGRF are in this part of the Wiki page
https://github.com/rollerderby/scoreboard/wiki/Preparing-a-Game
(The Data Management screen is mentioned here - https://github.com/rollerderby/scoreboard/wiki/Data-Management )

This is a relatively new feature, having been available since the first V5 release, so as long as you're using a V5 release, you'll be good to go. The only thing that as a user I make sure I pass on, is to only click on the _Import_ button **ONCE**. It may not look like it's doing anything, but depending on the device and game file etc, it make take a minute or two before it appears under the Game header. Having found out the hard way, if you click import more than once, it will import more than once and you'll end up with 4 copies of each skater and official.... 

Note also that both skaters **and** officials will be imported [Officials will be populated into the **IGRF** tab] . It'll appear in the Data Management screen like this
(referencing the **2022-12-04 Blocka Nostra vs. All Stars (Prepared: 0 - 0)** line)
![image](https://user-images.githubusercontent.com/28804763/216752623-b032b06b-3ee8-4167-8c82-d28e871134e6.png)
That will then be able to be selected in the _Start New Game_ menu in the Operator panel
![image](https://user-images.githubusercontent.com/28804763/216752645-9c327706-1da2-4633-948c-fa7b072e0a41.png)

When exporting IGRF, don't forget that you now need to have a blank copy of the statsbook hosted inside CRG
![image](https://user-images.githubusercontent.com/28804763/216752447-820774db-05ee-4204-bc4e-8e38f8cd11ab.png)
EG: This file would be in the same folder that scoreboard-Windows.exe_ is in
If it was in a subfolder, lets say _statsbook_ for the sake of the argument, the file path in the folder would need to be **statsbook\wftda-statsbook-full-us-letter.xlsx**

Hope this helps

~Bullseye

**Comment by frank-weinberg** [comment]
Some additional notes:

- 5.0.10, which I hope to release within a week, will have an indicator when an import is in progress, resolving the "it looks like it's not doing anything" problem.

- Importing an IGRF will mark "Captain" and "Not Skating" flags, if that info is included in the IGRF as per the Statsbook Manual.

- You can also copy and paste whole rosters at once, as long as the columns are in the correct order. Just paste into either the name or the number field of the "Add Skater" row. This works for tables from HTML, spreadsheet programs, and probably other sources and will update existing skaters if numbers match. Note: This method will import everybody as "Skater".

**Comment by atkinsonm** [comment]
I see, thanks for explaining! I forgot the "upload statsbook" option on the data management page. My league likes to do things their own way for unsanctioned bouts but I'll see if they would be willing to give me a statsbook format or I'll see if converting what they give me into statsbook will save myself some time.
