### ISSUE TITLE
[FEATURE REQUEST] Keep websocket data model consistent between versions

### ISSUE THREAD

**Issue by mpapazog** [rollerderby/scoreboard#575]
As a third-party developer creating custom stream graphics using the websocket interface of the derby scoreboard application, I find it hard to keep up with changes in the data model. Every time there is a new version out, I have to verify what has changed and modify my state tracking code to support the new version, even if I am not planning to make use of the new version's added features.

It would make it much easier for third parties, if existing elements in the data model were not moved around between versions. Additional elements could be added, of course, to support new features. It would also help to have publicly available documentation on what elements have been added between versions.

The current model seems pretty good. It could become the standard going forward.

**Comment by frank-weinberg** [comment]
I have just double checked and since 5.0.0 there have been only additions and no removals or renames in the WS data. And I intend to keep this up as much as possible.

If I have to make a breaking change it will 
- trigger an increase of at least the middle part of the version, if not the major version
- be mentioned in the release notes for the new version

And the full overview of which elements are available in which version is on the wiki: https://github.com/rollerderby/scoreboard/wiki/WebSocket-Channels

Does this address your concerns?

**Comment by mpapazog** [comment]
The wiki page certainly helps. Thank you.

My intention was more to give feedback, so you may close this case, as I clearly see that my concern has been heard.

In general, my wish would be to not make breaking changes ever, if possible. From the perspective of an external entity using the websocket interface, the time between releases can seem quite short.

I understand that this is not meant to be an enterprise grade API, or an API in any sense. In that world, it is not uncommon for an interface to be supported for 5+ years, preferring to deprecate endpoints/information elements rather than remove them, if reorganization is necessary.

**Comment by JeneralPain** [comment]
Totally fair and makes sense.Thank you for raising this. Sent from my iPhoneOn 14 Feb 2023, at 7:56 pm, mpapazog ***@***.***> wrote:﻿
The wiki page certainly helps. Thank you.
My intention was more to give feedback, so you may close this case, as I clearly see that my concern has been heard.
In general, my wish would be to not make breaking changes ever, if possible. From the perspective of an external entity using the websocket interface, the time between releases can seem quite short.
I understand that this is not meant to be an enterprise grade API, or an API in any sense. In that world, it is not uncommon for an interface to be supported for 5+ years, preferring to deprecate endpoints/information elements rather than remove them, if reorganization is necessary.
