### ISSUE TITLE
Feature Request - SK panels

### ISSUE THREAD

**Issue by AmyFeralFouler** [rollerderby/scoreboard#599]
I'd like to request a SK panel that is just the SK piece of the operator panel.  I believe this will give us a simplified option for SBO at the same time by allowing the timing to be controlled by the JT panel.  This will help with finding more SBOs since so many NSOs seem to be intimidated by the Operator Panel

*rough mockup (thrown together with snips of the operator panel)
![image](https://user-images.githubusercontent.com/63978266/227795594-e151065c-fb29-4f44-ba59-ec72d1e743bb.png)

**Comment by frank-weinberg** [comment]
Just to acknowledge this: I think this feature makes sense and want to add it. But it is too much work to just squeeze into a weekend, so it might take a bit until it gets done.

**Comment by atkinsonm** [comment]
In this scenario do you envision that each SK would have access to their own device e.g. tablet and able to enter points this way?

The potential of this is huge. Having digital SK means that the SKs don't necessarily need to sit together since the shared info like jam numbers and star passes are synchronized. With eJT added, you arguably don't need an SBO at all (at least during the game).

**Comment by frank-weinberg** [comment]
This is done as part of the frontend rewrite for 2025.*
