### ISSUE TITLE
[FEATURE] Change timeouts without removing timeout 

### ISSUE THREAD

**Issue by WishboneBreaker** [rollerderby/scoreboard#603]
Currently if you want to correct the number of timeouts after the next jam has started, you navigate a prompt which prevents you from doing other functions for the jam in progress while you're making that change.

The number needs to be editable in a simple text box on the fly and/or with a +1/-1 toggle.

And if you have to remove a timeout, you currently must stop the game clock (disrupt game flow) start a new timeout and then assign the right type.

Again, a simple text box or +/- control would not disrupt game flow.

**Comment by frank-weinberg** [comment]
Editing the number directly is not possible with the data model in CRG 4/5, just as it is with the total score. The detailed game data is the source of truth and the values displayed on the scoreboard are derived from that.

That being said, I totally get your point about opening popups during a jam being problematic. I'm somewhat uncomfortable doing that myself. Obviously this applies to score even more than timeout numbers. So I'd like to reframe this ticket as a feature request to make as much of the publicly visible information as possible adjustable without the need to open a popup.

And just this way of putting it has made me come up with some new ideas:

1. On the SK sheets next to each jam add an "edit" button. Clicking it  toggles inline edit controls for this jam and this team, including at least:
   - +/- buttons on each scoring trip
   - buttons to delete the jam and add a jam or timeout next to it.
2. Add (differently colored) rows to the SK sheets that indicate timeouts, also with an edit button.

This should address the problem of requiring popups for things that should or must be changed outside of a timeout. And my gut feeling is that it would also be more intuitive than the current interface. What do you think?

**Comment by WishboneBreaker** [comment]
Thank you for being open to the idea. I appreciate the thought you've already put behind it. There's so many dedicated folks who never get the recognition they deserve.

For the score editing portion of your reply (issue #604) I'm going to bring back the suggestions to others and get their impressions, so I'm not speaking for them. It sounds like a good idea, but I don't think it's fully addressing the concerns I've heard. 

As for me, there's times where getting points up on the display as fast as possible is paramount and seconds and even portions of seconds matter. There's rules-mandated time limits to when the display can change, but no time limit on when the paperwork can change. The fastest way to change the score immediately without looking around the operator display and clicking with my mouse in tiny spaces is to use the +/-1 hot keys I have. However, doing this changes the displayed jam score and now the display is inaccurate and causes confusion to the teams and JR. So like maybe a button/option that's "add/subtract score without changing current jam displayed score." Then for example I could set that hot key, for instance, to shift+[increment score]. And behind the scenes maybe the coding adds a new unnumbered trip to the previous jam or an adjustment jam before the current jam that shows a "jamless score change". Then without looking at the keys or mouse or screen I could adjust the displayed score without taking my eyes off the track. Then maybe in my next time out I could edit the score properly in the score sheet where my jamless point belongs and delete the extra jamless data. Or like, again in a timeout or halftime situation, I could click on the jamless points, click it, and navigate some options to "apply this point adjustment to jam 12, trip 2." So the displayed score would not change back and forth as I add the points to the proper place and delete the adjustment points.

Just my thought on a way to implement something that addresses what I'm hearing as the concern. 

I do think the editable timeout idea in the score sheet area or similar would address the timeout request I'm bringing you in #603. There's no mandate that timeouts displayed must be accurate by x time, so if that one is possible to edit without a timeout, and without opening popups etc that changes screen focus away unnecessarily, then I believe this would help the situations we've had in game.

**Comment by frank-weinberg** [comment]
While I'm not disputing that there is this pressure of making score adjustments super fast, I am firmly convinced that the fact that it is there is primarily a problem with our rules and procedures.

---- Sidetrack

- The rule about when score changes are allowed outside of the last 2 minutes is too strict. At least here in Europe general consensus is that during a jam you should be focused on the jam in progress exclusively. So the rule turns into "Score changes are only allowed until the start of the next jam all the time" in practice. Changing the limit from "end of the next jam" to "start of the jam after the next one" would add a full lineup time including the opportunity of taking an OTO without affecting the score displayed during a single second of actual gameplay. (And since this lineup period should include a routine comparison between score sheets and scoreboard, this would also allow the crew to catch it if a late score change was not added correctly or at all to the scoreboard. - The most common source of OS Offsets in my experience.)
- In my opinion if a JR brings a last second score change they should always call an OTO if the change does not show up on the scoreboard before jam start. Especially when it must be there by then (which is de facto always with the current rules).

---- end Sidetrack

Of course I'm aware that the software has to be used with the rules and procedures in place and not the ones we'd like to have.

With that off my chest let's look at your suggestion. First, adding adjustments as an extra object in the data model and applying them to a scoring trip later is possible in principle. But when looking at the details I see a lot of complications:

- First, while Shift-"+/-1" works well for a compatible keyboard setup (some people use only speed score keys, some have "-1" on Shift-"+1" - they would have to find another way to integrate this) the functionality would still need to be a second set of +/-1 buttons in the UI.
- Having a toggle that switches the function of the existing +/-1 buttons is worse IMO as accidentally activating this toggle will set you up for a decisively not fun time.
- Then, you'd need a way to store multiple corrections and a way to indicate to the software that you are done with entering one adjustment and want to start a new one.
- We also would want to block statsbook export as long as there are unassigned adjustments. This needs UI to make it clear to the user what is happening.
- We would also need to record when each adjustment was recorded in order to properly set (or not set) OS Offsets when it is applied.

Overall while this is doable it would be nontrivial. And it feels a lot like this would be another instance of "The software gets harder to use for newbies to support a feature that's only useful for a relatively small set of expert users."

I'm also not convinced it's needed. I understand why people like you would feel more comfortable with it, as it's closer to what you've been used to for years. But as far as I can see the one scenario where this really would come into play is a last second drive by adjustment by a JR. For these, with the current interface I can pretty consistently get the change entered by the time the JR is at the Jammer line, if the score table is at turn 1. With the proposed interface, I believe it's possible to get it to the point where an experienced SBO can consistently get the change made in the time it takes a JR to get from a turn 4 score table to the Jammer line. While still having a finger on the "Start Jam" key. (You can already activate edit mode for the last jam as the JR approaches. And often you'll have an idea what change is likely to come, so you can even move your mouse to the corresponding button. And note that edit mode would probably make the row larger in order to accommodate the extra buttons instead of trying to squeeze them into the existing space.)

**Comment by WishboneBreaker** [comment]
Thank you for the reply and thorough feedback.

> Of course I'm aware that the software has to be used with the rules and procedures in place and not the ones we'd like to have.

Absolutely agree! There's more than one rule I'd change if given a magic wand.

> * First, while Shift-"+/-1" works well for ...

I'd say one of the great things is how everyone can customize their hot keys based on their preferences. Or choose to not use a keyboard at all.

> * Then, you'd need a way to store multiple corrections and a way to indicate to the software that you are done with entering one adjustment and want to start a new one.

See comments at bottom 

> * We also would want to block statsbook export as long as there are unassigned adjustments. This needs UI to make it clear to the user what is happening.

This is a great idea!

> * it feels a lot like this would be another instance of "The software gets harder to use for newbies to support a feature that's only useful for a relatively small set of expert users."

It does not feel that way to me, though. 

> I'm also not convinced it's needed. 

I am

> it's closer to what you've been used to for years

But it's not that, actually. The BASIC functions, the rules-mandated functions of a successful scoreboard should/would not require looking at the screen during a live jam and using the mouse and clicking on what feels to the user like 4x4px boxes. 

> the one scenario 

This is not the only scenario. I'd say that's the most common. Another might be that the SBO just fucked up. Another might be that the SK fucked up. I've fucked up live on the ESPN stream. What is nice is being able to edit a fuck up without taking eyes off the live new jam and without putting up factual errors onto the current display or stream. Maybe others disagree. That's ok too. I'm giving my synthesis of feedback I've gathered from my league/region/cohort.

> I can pretty consistently get the change entered by the time the JR is at the Jammer line, if the score table is at turn 1. 

Awesome! Just like with the hotkeys and other things, not everyone has this experience or track set up, though. We start from a place of assuming that we don't all have a shared experience, right?

> experienced SBO 

Anything I'm suggesting personally is coming from a >1 group of "experienced SBO"s, and not my own singular personal preference. Hopefully that can be appreciated. Nothing I'm suggesting here is coming from the place of making it easier for newbies. Nor am I suggesting or attempting a subtext that anyone reading this is not experienced or valued.

**Alternative suggestion if my original is tricky:** What if the proposed "_edit score without changing current jam score_" (ESWCCJS) feature instead of entering an unnumbered jam or unnumbered trip instead changed the entry to the last trip of the previous jam? You'd still probably want the export warning on the paperwork (if needed, only a small portion of users use this feature -- at least, I mean, uses that export feature without needing a validation/comparison before exporting) that "the ESWCCJS was used in Jam X and applied in Trip Y of Jam X-1." Any time in Jam X I apply the override (which in my mind there would be two. One for each team), it would apply to the last trip of Jam X-1 for that team. I think this would solve the problem of where to assign the edit. It would ALWAYS go in the last trip of currentJam-1. And when I'm done adding the adjustment, when I let go of the ESWCCJS button, any new score addition is applied to the current trip as usual.

I'm sure you have a procedure for triaging and prioritizing and voting on features. If the suggestions I'm bringing you from my league/region/cohort don't sound common, perhaps it's something that could be included in the next "help us prioritize changes" process? I totally get it that some changes are easier than others, and some changes are unfeasible, and some seem more critical to one user group and not another.

For instance, here's a user reaction I got "Revert points system back to previous system, or at least make it an option to do so. Most people don't need or even want to generate the whole statsbook from the the data in the scoreboard." With the assumption here again that I'm not bringing you feedback from newbies. This is of course just one person's feedback. I personally get it that we can't "revert" the whole thing. But an option somehow to ESWCCJS is the kind of thing that I'd think would address this complaint that I'm given.

**Comment by frank-weinberg** [comment]
> Thank you for the reply and thorough feedback.

Thank you for taking the time of coming over here and helping me understand the perspective of you and your peers as well as working on solutions.

> Anything I'm suggesting personally is coming from a >1 group of "experienced SBO"s,

That was my understanding. When I was saying I expect experienced SBOs to able to do this, the intended implication was that I'd expect this group to be able to do this once you get used to the interface.

 > The BASIC functions, the rules-mandated functions of a successful scoreboard should/would not require looking at the screen during a live jam and using the mouse and clicking on what feels to the user like 4x4px boxes.

While you have not convinced me to personally join the "this is a mandatory feature" camp, I can see why some people take that stance. And there is no question that it is a useful feature. If we can find a way to implement it that does not negatively affect users that don't want to use it, which I believe we can, it will definitely be implemented.

Just to  make sure we are on the same page, this is what I'd consider the requirements:
- I will  implement the edit feature described above and it will be described in the documentation as the default way to change the score for past scoring trips.
- The feature discussed here offers a way of recording score adjustments without the operator taking their eyes off the track. As such the focus is on the recording an adjustment part being usable with keyboard shortcuts only as requiring a mouse would defeat the purpose. But for applying shortcuts to a scoring trip later on mouse use is an option.
- It should be easy to pick the scoring trip to apply the adjustment to, so this can regularly be done during the next lineup, taking the adjustment off the UI and the operator's mind. (But it must also be possible to leave the adjustment unassigned for an indefinite amount of jams. And it must be possible to discard an adjustment without applying it.)
- A score adjustment always affects the total score of the team (but not the jam score) at the time of recording. Based on which jam it is applied to and when this happens there may be OS offsets and/or total score changes at the time of application as follows:
   - If it is applied to a jam that was allowed to be edited at the time of recording, there are no OS offsets or total score changes.
   - If it is applied to a jam that could no longer be edited at the time of recording, but the jam during which it was recorded can be edited at the time of application, an OS offset will be added to the jam it is applied to and the total score change from the time of recording will be reverted.
   - If it is applied to a jam that could no longer be edited at the time of recording and the jam during which it was recorded can no longer be edited at the time of application, an OS offset will be added to the jam it is applied to and an inverse OS offset is applied to the jam it was recorded in. The total score remains.
   - If the adjustment is discarded without applying it, the jam during which it was recorded is affected as if it had been applied to a jam that could not be edited at the time of recording.
   - If applying an adjustment would make the trip score negative, the result is the same as if an adjustment that sets the trip to 0 was applied and a second adjustment containing the remaining amount was discarded.
- As long as there are unassigned adjustments, no statsbook can be exported for the game.
- The feature is considered advanced and thus it is disabled by default, hiding all it's UI elements. It can be enabled with a button in the top row and the setting is stored as an operator setting.

> Alternative suggestion if my original is tricky

The part you are suggesting an alternative for is not tricky. From a backend perspective this is quite straightforward. The more difficult part is the UI.

Thoughts on the UI:
- All UI elements for this feature are grouped together in a segment right above the score sheets.
- There is a +1 and a -1 button that affect the active adjustment or create a new one if none is currently active. These can be assigned hotkeys.
- 4 seconds after the last change (same as for trip advancement after a score change) or the moment the jam ends (whichever comes first) the active adjustment closes. There is also a button allowing for manual closure, if an SBO wants record multiple adjustments right after each other.
- Once an adjustment is closed, it's points amount can no longer be changed. (This is required to allow the OS offset logic to be applicable.)
- The UI lists each closed and unapplied adjustment along with the jam it was recorded in, dropdowns allowing to select the Jam and scoring trip to apply it to, and buttons to apply or discard it.
   - If the adjustment is recorded during the second or a later scoring trip, the dropdowns are preset to the prior scoring trip of the current jam. If it is recorded earlier, they are preset to the last scoring trip of the previous jam. (This is my gut feeling as to what would most commonly be the correct jam. But I'm open to always making it the last trip of the prior jam.)
- Once an adjustment is applied or discarded, it is removed from the UI.

**Comment by WishboneBreaker** [comment]
Some feedback on the proposed from my cohort (my feedback will come in a separate reply once I've worked through it in my head tomorrow):

The key thing is that we need to be able to adjust the score via hotkey

As long as I can rack up an infinite number of "unassigned" adjustments

I need to be able to run a whole game using the score adjustment hotkeys

**Comment by WishboneBreaker** [comment]
As we're hosting a multi game event on 29-30 April, I think some additional feedback will come in then.

**Comment by JeneralPain** [comment]
The more data the better! Sent from my iPhoneOn 17 Apr 2023, at 12:25 pm, WishboneBreaker ***@***.***> wrote:﻿
As we're hosting a multi game event on 29-30 April, I think some additional feedback will come in then.

**Comment by WishboneBreaker** [comment]
> receiving

One thing we got feedback on from BOTAS was the freezing/crashing, so at the OPE!n we'll implement a policy to restart in the morning and restart after every 2 games.

And of course we'll have a backup laptop ready to connect to the overhead display if something happens and the computer swap seems like the most expedient solution in the moment.

**Comment by WishboneBreaker** [comment]
> The more data the better! Sent from my iPhoneOn 17 Apr 2023, at 12:25 pm, WishboneBreaker ***@***.***> wrote:﻿ As we're hosting a multi game event on 29-30 April, I think some additional feedback will come in then. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

One thing we got feedback on from BOTAS was the freezing/crashing, so at the OPE!n we'll implement a policy to restart in the morning and restart after every 2 games.

And of course we'll have a backup laptop ready to connect to the overhead display if something happens and the computer swap seems like the most expedient solution in the moment.

**Comment by JeneralPain** [comment]
For freezing, id like to separate that to its own issue.Can we get more detail on the problem? Like what caused it etc. thanks Sent from my iPhoneOn 17 Apr 2023, at 12:43 pm, WishboneBreaker ***@***.***> wrote:﻿

The more data the better! Sent from my iPhoneOn 17 Apr 2023, at 12:25 pm, WishboneBreaker @.> wrote:﻿ As we're hosting a multi game event on 29-30 April, I think some additional feedback will come in then. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: @.>

One thing we got feedback on from BOTAS was the freezing/crashing, so at the OPE!n we'll implement a policy to restart in the morning and restart after every 2 games.
And of course we'll have a backup laptop ready to connect to the overhead display if something happens and the computer swap seems like the most expedient solution in the moment.

**Comment by WishboneBreaker** [comment]
> For freezing, id like to separate that to its own issue.Can we get more detail on the problem? Like what caused it etc. thanks Sent from my iPhoneOn 17 Apr 2023, at 12:43 pm, WishboneBreaker ***@***.***> wrote:﻿ The more data the better! Sent from my iPhoneOn 17 Apr 2023, at 12:25 pm, WishboneBreaker @.> wrote:﻿ As we're hosting a multi game event on 29-30 April, I think some additional feedback will come in then. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: @.> One thing we got feedback on from BOTAS was the freezing/crashing, so at the OPE!n we'll implement a policy to restart in the morning and restart after every 2 games. And of course we'll have a backup laptop ready to connect to the overhead display if something happens and the computer swap seems like the most expedient solution in the moment. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

Gosh, i'm not even sure what the issue is. There were two meltdowns due to scoreboard at Clover Cup. The second one resulted in a 25 minute timeout. Not due to operator error, I'm told.

An organizer of the Y'all Stars event told me a similar thing happened there.

Then at BOTAS "Here’s my best try at this: My experience from BOTAS was that the longest time out happened when the cached scoreboard auto save things maxed out the hard drive? Then the concurrent overlay and broadcast stuff slowed things down a touch more."

What I'm hearing is it seems to be a memory cache thing.

Sorry to reply on this thread, I'm unsure how to start a new one. Details beyond what I've listed could be obtained if you're interested. I'd just have to reach out to those folks for any additional details they have that you think might be useful 

*I mean, I'm not sure how to break apart one thread for another. Or even if it's something you're interested in.

**Comment by bullseye555** [comment]
@WishboneBreaker - Started #606 for the crashing bug

**Comment by frank-weinberg** [comment]
>I need to be able to run a whole game using the score adjustment hotkeys

Based on the requirements above, this would be possible in principle. I would consider actually doing it misuse of the software and obviously the jam score would be stuck at 0, but you would have the expected total score at all times.

**Comment by WishboneBreaker** [comment]
> but you would have the expected total score at all times

Many folks only care that they can display the rules-mandated data. Jam total is not mandated. And of course this leads back to my original request to have the option to take jam total off the overhead display.

I like where my request has evolved into, so I'm not now repeating the request for the option to remove it from the overhead display. But this is an example of the feelings of the folks who  just don't care about the unnecessary stuff. Not that you need to please all of them, of course.

**Comment by frank-weinberg** [comment]
Inline edit for the SK sheets is working. Definitely requires some focus to navigate the buttons. But at least people should be able to figure out which button they need without reading the documentation most of the time.

![Screenshot_20230506_234903](https://user-images.githubusercontent.com/34135287/236647883-f3248ba9-cca3-4e66-a6e3-94ceede3911d.png)

**Comment by JeneralPain** [comment]
The real crisis here, 31min OR heh Otherwise like the direction. Sent from my iPhoneOn 7 May 2023, at 7:57 am, frank-weinberg ***@***.***> wrote:﻿
Inline edit for the SK sheets is working. Definitely requires some focus to navigate the buttons. But at least people should be able to figure out which button they need without reading the documentation most of the time.
