### ISSUE TITLE
Differentiate between alternates and skaters not rostered

### ISSUE THREAD

**Issue by atkinsonm** [rollerderby/scoreboard#658]
## Background

On the teams data management page and in a game, there are flags for "skater" and "not skating". Choosing "not skating" takes a player out of the selection for lineup tracking. In the backend, the value is written to the data store as `ALT`, which implies that the "not skating" flag is meant for alternates.

## Problem

There's no way to distinguish between alternates and absent/non-rostered members for a game. This is fine for setting up new teams for every game, but makes it difficult to reuse teams. Synching teams changes in-game will affect the teams in the data management page, so that's not desirable when marking alternates or removing members from the roster, but also prevents any other changes from being synched. It's possible to make the right changes if team changes are kept exclusively on the teams data management page and the teams tab in-game is used exclusively for in-game players, but this can be confusing for operators.

## Expected Behavior

Separate categories for "alternates" versus "not skating" to indicate to an operator how those flags are intended. Alternates should appear on the roster but not the lineup tracking screens unless they are changed to "skating". "Not skating" players should be absent from all active game screens and appear only on the teams data management page.

## Actual Behavior

"Not skating" appears in both places and can be synced. Players need to be removed entirely from a team to be marked as not playing in a game. Doing this while sync changes is enabled will permanently remove that player from the team for future games, which may not be what the operator intends.

**Comment by frank-weinberg** [comment]
The usage of the letters "ALT" for this flag is due to historical reason and should not be interpreted as having a meaning.

These roles are created primarily from a paperwork POV - There are the people skating and those that appear on the IGRF as part of the charter but not the roster. Then there is Bench staff who could theoretically be expelled, in which case they would have to be recorded on the IGRF. Everybody else is irrelevant to the game and thus can be removed from the per-game-team.

I don't see what use an additional category would have.

**Comment by atkinsonm** [comment]
If the non-skaters are hidden in the roster view then I agree, the extra category would not be necessary.

**Comment by atkinsonm** [comment]
Closed in favor of #657
