### ISSUE TITLE
Add option to whiteboard display to change text color of penalties in the second half

### ISSUE THREAD

**Issue by GorramRob** [rollerderby/scoreboard#66]
Feature Request -- add an option to change the font color of penalties incurred in the second half of a game on the whiteboard display.

**Comment by official-sounding** [comment]
a few other style/highlighting tweaks to the PT sheet, from feedback in the FB group:

* Highlight Penalties from the current jam (through to the start of the next jam)
* Highlight Skaters currently in the jam, as selected from the LT/Operator screen
* Make the background of the PT sheet black

**Comment by AdamSmasherDerby** [comment]
As a matter of style, how should we be allowing users to select selectable options?  Ruleset editor? Policies? Config File? Switch on the PT entry page itself?  The actual implementation of the color change doesn't seem that difficult, but the UI design is something that should have some thought applied to it.

**Comment by bullseye555** [comment]
Can I add one to this - an option in Ruleset (or policies or config, whichever path it goes down) to be able to set # penalties in a game. Then when you're running a 20 min half game with reduced number of penalties, the PT and IWB screens will have their colour highlights based on that (eg: set 5 penalties instead of 7, and it will yellow at 3, orange at 4 and red at 5 etc)(can also open another ticket, if deemed too far from the original to be included in it) 

Personally, I'd be adding something like this to the ruleset editor, however it would depend on what other functions are made available, and something like the original request in config

**Comment by admdikramr** [comment]
Visual indication of "Period 1" penalties as different from "Period 2" came up for all three CHNSOs (including myself) at the WFTDA Continental Cup in Kalamazoo last weekend.

Using a different font color is one option. Greying the background is another option (more similar to paper PT).

**Comment by brian-brazil** [comment]
This was done in #112, they're now bold/not-bold.
