### ISSUE TITLE
File Name of Selected Logo not displayed on Team edit screen

### ISSUE THREAD

**Issue by JamPain** [rollerderby/scoreboard#661]
When editing the team the assigned logo is saved but the filename is not displayed when the team is edited again later.

Steps:
- Create new team
- Select logo file -> file name is displayed
- add skaters
- leave team edit screen
- edit team -> **logo file name is NOT displayed**

Ther value is saved but not displayed. Can be checked by:
- Create game
- select team -> logo is set and File name is displayed

Expected:
File Name of selected logo is displayed on team edit screen

**Comment by JeneralPain** [comment]
Can you share the file name and details?Is it in the right folder? Sent from my iPhoneOn 25 Aug 2023, at 08:09, JamPain ***@***.***> wrote:﻿
When editing the team the assigned logo is saved but the filename is not displayed when the team is edited again later.
Steps:

Create new team
Select logo file -> file name is displayed
add skaters
leave team edit screen
edit team -> logo file name is NOT displayed

Ther value is saved but not displayed. Can be checked by:

Create game
select team -> logo is set and File name is displayed

Expected:
File Name of selected logo is displayed on team edit screen

**Comment by JamPain** [comment]
I placed a transprarent PNG Gemstones.png in \crg-scoreboard_v2023.3\html\images\teamlogo before I started the config.

As explained, the Image is assigned to the team and displayed in game config as well es on the main scoreboard view.

The only thing missing is the selected filename being displayed on the team config screen.

**Comment by JeneralPain** [comment]
Just be mindful of your tone, we're all volunteers supporting a FREE piece
of software.

Could you provide screenshots of everything you have done so we can better
visualise your concern?
Could you provide the CRG Version?
Could you provide the Operating System Version?

I want to see if I can replicate the problem in the same environment.

**Comment by JeneralPain** [comment]
So I just did a fresh install of CRG2023.3 on to my Windows 11 machine
Copied the logo "CFA_Logo.png" to
the C:\temp\crg-scoreboard_v2023.3\html\images\teamlogo folder
Went into Manage Data > Teams > New > Selected Logo I uploaded
No issue found.

Also checked via the
Main Scoreboard Operator > Teams Tab > Selected team created > Logo showed
correctly.

At the minute, I cannot find fault, however, if you could provide the
following:
Could you provide screenshots of everything you have done so we can better
visualise your concern?
Could you provide the CRG Version?
Could you provide the Operating System Version?
Did you copy/paste a new downloaded version over an older version? (If yes,
this sometimes has had some exotic bugs kick out due to the data management
and the way data is handled).

**Comment by frank-weinberg** [comment]
@JamPain Fix will be in the next release.

@JeneralPain What problem with Jam's tone do you see? I don't see anything wrong there.
