### ISSUE TITLE
Penalty Box Timer

### ISSUE THREAD

**Issue by katpet** [rollerderby/scoreboard#673]
Hi, I wanted to put on your radar this feature I've been working on, adding a mobile penalty box timer UI to the CRG scoreboard, inspired by the jam timer UI. This probably falls in the category of features nobody has actually asked for, but for some reason I felt compelled to try it. At this point it has survived a couple days of scrimmages in our junior league.

I'm wondering if this is something you'd consider having a pull request for. I expect some more polish might be needed before it's ready. And I understand if a sizable change to the server code like this seems too risky..

There's a docs page here: 
https://github.com/katpet/scoreboard/wiki

The latest release, called crg-scoreboard_v2023.4_pbt_v0.3, is made from the 2023.4 release plus this new feature; so, I've replaced the main jar file and added some html and javascript files:
https://github.com/katpet/scoreboard/releases

-Kat 
(an NSO for Seattle Derby Brats)

**Comment by JeneralPain** [comment]
I feel like this is a conversation myself and bullseye had about trying to make the processes for NSOs easier. So they don’t have to worry about trying to track 3 people with a stop watch and a pen. I feel like that crazy high workload deters people from doing paperwork.Sent from my iPhoneOn 31 Oct 2023, at 14:21, Katrin Bratland ***@***.***> wrote:﻿
Hi, I wanted to put on your radar this feature I've been working on, adding a mobile penalty box timer UI to the CRG scoreboard, inspired by the jam timer UI. This probably falls in the category of features nobody has actually asked for, but for some reason I felt compelled to try it. At this point it has survived a couple days of scrimmages in our junior league.
I'm wondering if this is something you'd consider having a pull request for. I expect some more polish might be needed before it's ready. And I understand if a sizable change to the server code like this seems too risky..
There's a docs page here:
https://github.com/katpet/scoreboard/wiki
The latest release, called crg-scoreboard_v2023.4_pbt_v0.3, is made from the 2023.4 release plus this new feature; so, I've replaced the main jar file and added some html and javascript files:
https://github.com/katpet/scoreboard/releases
-Kat
(an NSO for Seattle Derby Brats)

**Comment by frank-weinberg** [comment]
This is definitely too big of a change to put in a 2023.x release - they are supposed to focus on stability after all.
But I have been thinking about adding a PBT screen for 2025.x myself. And reading through your dev notes I recognize some ideas regarding how to do stuff on the backend. So I will definitely have a closer look at this before I start implementing anything myself.

Things I wonder that you may be able to answer as you have practical experience:

- How much does it affect timing that people should be looking for the skater to touch the seat but also need to look at the screen to hit the start button?
- Are there issues with the WiFi connection lagging for a moment and timers being off due to that? (The frequency I see such lag as ePLT is way too high for me to consider using ePBT in a sanctioned game.)
- How do people deal with a situation where the box crew misidentifies a Jammer as a Blocker or vice versa and only realizes after the clock started?

**Comment by JeneralPain** [comment]
So the "lag" question is often caused by a poorly designed WiFi network.
We've never had a LAG problem at any event we've run, but then I make sure
we're not crossing over channels with the venue or otherwise.

I have seen ePLT being used at sanctioned games in AUS and never
experiencing such issues. If there is a common point of lag, I'd have to
investigate separately with you on that side of things.
Given you aren't on socials and can only reach you via here, it makes
troubleshooting that pretty much impossible.

The "looking at the screen" is no different than a stop watch, so I find
that argument is a potato potato type argument.

That said, totally agree its a too big change to put in a minor release, so
fully agree with holding it back.

**Comment by bullseye555** [comment]
A couple of valid questions Frank.

Let me think on them and I'll comment again in the next day or so

**Comment by frank-weinberg** [comment]
> The "looking at the screen" is no different than a stop watch

I don't know what stopwatch you are using but with every one I have held in my hand so far I was able to rest my finger on the button and press it without looking at the watch. That does not work with a touch screen.

> So the "lag" question is often caused by a poorly designed WiFi network.

Yes. People are using cheap WiFi routers placed on a table and if the pack is between the router and the tablet that can be enough to temporarily block the signal. No big deal for PLT, maybe tolerable for PBT (or JT) in a scrimmage or if the alternative is cancelling the game, but definitely not what you want for higher level.

**Comment by atkinsonm** [comment]
We'd also have to consider how the scoreboard behaves in a situation with ePBT and paper PT. I'd be okay with saying that ePBT would only be available if coupled with ePLT.

Some comments for @katpet on the wiki:

> that skater is automatically also fielded (if they weren't already)

There's a situation in which a captain can receive a penalty even though they are not fielded. This special case may need to be considered.

> marking box trips

I really like this. That would cut down on the responsibilities of the ePLT.

Overall I like this idea and think it has potential to simplify NSO positions, increase accuracy, and perhaps even minimize the number of NSOs required. It also comes with some concerns about lag, reduced redundancy, and additional conflicts (e.g. a skater sits but the PLT hasn't marked them as fielded due to operator error). We'd likely need people to test it for a while in unsanctioned games to work the kinks out.

**Comment by katpet** [comment]
> This is definitely too big of a change to put in a 2023.x release - they are supposed to focus on stability after all. But I have been thinking about adding a PBT screen for 2025.x myself. And reading through your dev notes I recognize some ideas regarding how to do stuff on the backend. So I will definitely have a closer look at this before I start implementing anything myself.

Yes, totally understood that something like this wouldn't go into a point release.. 

> 
> Things I wonder that you may be able to answer as you have practical experience:
> 
> * How much does it affect timing that people should be looking for the skater to touch the seat but also need to look at the screen to hit the start button?

You can select the skater before or after they sit, or switch the selection if it wasn't correct, up until the end of the penalty. Since jammer numbers are already set, you'll only be dealing with selecting blockers, so will always have 30 seconds.  In practice that may still not be enough time, so yeah, mistakes will be made.

I'm thinking there are some UI improvements that could make selecting the skater easier, like highlighting any fielded blockers in the list that the PLT has already selected.

Selecting a skater is only useful for the new penalty tally, which I see more as a double check for what the PLT is doing. I could imagine not bothering with the skater number tracking and just using this UI as an alternative to a phone app for non-sanctioned games. You still benefit from having timers automatically stop/start between jams. We've run across people with newer phones (android I think) who couldn't get the penalty box app from the app store, so it's another way to make sure there's always a free app available for anyone who wants to do penalty timing.

> * Are there issues with the WiFi connection lagging for a moment and timers being off due to that? (The frequency I see such lag as ePLT is way too high for me to consider using ePBT in a sanctioned game.)

Definitely a concern. I imagine clocks might freeze for a moment but would correct themselves. Our penalty timers this weekend who tried this out didn't mention noticing lag or glitching, but we'll continue look out for it.

> * How do people deal with a situation where the box crew misidentifies a Jammer as a Blocker or vice versa and only realizes after the clock started?

A jammer could sit in a blocker seat, and their number could still be applied there. If a blocker sits as a jammer that would be a mistake that we can't do anything about (if you care about the penalty tally).
