### ISSUE TITLE
Request from FB - USARS support

### ISSUE THREAD

**Issue by JeneralPain** [rollerderby/scoreboard#679]
[Anthony King]
I feel like I may have seen this discussed somewhere before, but if possible I would like to request the addition of USARS to the available rulesets.
We developed a workaround in its current form, but the major difference between USARS and WFTDA rules regarding official reviews is a sticking point. In USARS, an official review may be called as long as the team has a timeout. If they win the review, they keep the timeout, and if they lose the review they lose the timeout.
The scoreboard appears to be designed with two "banks" in mind, one for the timeouts, and a separate one for the official reviews. If it were possible to merge the two for the USARS ruleset, this could fix the issue?
The only other problem is USARS doesn't have a "star pass", but a "pivot break". This one is mostly semantics, and they function more or less the same, but if its possible to change "Star Pass" to "Pivot Break", that would probably solve any issue there.
I hope this isn't too much to ask. I really appreciate all your time and effort. Thank you for your consideration!

**Comment by JeneralPain** [comment]
have thought about this, changing the whole way the data is managed/handled would be quite a big uplift to support USARS. Changing the 'entire layout' to support USARS would then break it for CRG. So likely will need: 
- a different "main scoreboard" page for USARS
- different rulesets and data handling

In my eyes I feel like this would require a ground up re-write.

**Comment by frank-weinberg** [comment]
USARS plays by the so-called "International rules" administered by World Skate.

World Skate is a governing body that is 
a) deeply undemocratic and 
b) regularly trying to siphon off skaters and officials that the WFTDA affiliated Derby community has invested in educating in order to make money off the events they want them to play/officiate in.

Because of that I would not add support for their ruleset even if it was trivial to do. And as you say, it is not trivial.
