### ISSUE TITLE
Don't just remove a (seemingly random) Blocker when user adds too many

### ISSUE THREAD

**Issue by admdikramr** [rollerderby/scoreboard#686]
**Describe the bug**
1. Tap a blocker, i.e., tap the button in ePLT to choose the skater as a blocker. This is normal.
2. Tap another. Normal.
3. Tap another. Normal
4. Oops the team swapped out a blocker. Tap the fourth blocker -- this is where the issue occurs. It removes the blocker from Step 1, which is surprising, not always correct, and "silent" in the sense that it is not clear what happened. The result can often be that the wrong blockers are selected.
5. If you now tap the other two blockers, you should be ok, but they are already on the track.

Note that this does not occur for Pivot or Jammer, because there can only ever be one. 

**Proposed Solution**
Upon tapping the third blocker, rather than replacing an earlier blocker:
2. Open a dialogue that says "Too many blockers. Who should we replace?" which lets the user select who to replace, or allows the user to choose "unstaff all blockers" so that they can start over with a clean slate.

**Version:**
2023.5

**Comment by JeneralPain** [comment]
Hi Muffin,

Yes, if you for example did:

J1, P2, B3, B4, B5

Then B4 got swapped out, it'll go "well the first in was J1" so it knocks
out the jammer. Most people will move the blocker to the bench rather than
adding an additional pop up that is "what do you want me to do?" but we can
certainly look at a better way of handling this sudden change.

**Comment by admdikramr** [comment]
Yes, I agree that if a blocker is moved to the bench, we should not show the popup. The popup should only show if there is no "room" to add a blocker.

**Comment by JeneralPain** [comment]
Yes however I'm mindful that if we keep adding "pop ups" everywhere, people
will get frustrated because "its distracting".

The team have to look at the wider impact, the wider benefit when deciding
how to solve a feature request. As this is not a bug.

**Comment by frank-weinberg** [comment]
@JeneralPain Fielding a Blocker never removes the Jammer.

@admdikramr Your proposal makes a lot of sense from a UX perspective. Unfortunately it's quite involved to implement since the detection and handling of the replacement situation happens in the backend and backend-frontend-communication is only through the global state and stateless commands. And the logic for detecting when replacing is needed and who can be replaced is quite involved (Skaters in the box can't be replaced; there may be a 4th Non-Pivot-Blocker), so repeating it in the frontend in order to show the popup before sending any command is non-trivial.

I'll recategorize this as a Feature Request and will move it to the next major version - this is too big of a change to introduce right before post season starts.

**Comment by admdikramr** [comment]
Thanks Speedy. Makes sense.

**Comment by JeneralPain** [comment]
@Speedy - it was a comment trying to word out the concerns. Sent from my iPhoneOn 27 Mar 2024, at 04:51, Muffin ***@***.***> wrote:﻿
Thanks Speedy. Makes sense.
