### ISSUE TITLE
[BUG] Error: Unable to access jarfile

### ISSUE THREAD

**Issue by Captain-Emo** [rollerderby/scoreboard#690]
Hello,

I keep getting the following error when I try to run the Windows scoreboard executable:
"Error: Unable to access jarfile C:\Users\eklei\Desktop\Derby\scoreboard-dev\lib\crg-scoreboard.jar"

I downloaded the zip directly from Github, put the zip in the location I wanted the scoreboard to live (a folder on my desktop), and then unzipped it. I have Chrome [Version 123.0.6312.106 (Official Build) (64-bit)] and Java [Version 8 Update 401 (build 1.8.0_401-b10)], and I'm running Windows 10 Pro.

When I follow the directions in the ReadMe file to "Windows users: Run scoreboard-Windows.exe to start the script.", I immediately get the error. When I went to that folder, there is no crg-scoreboard.jar and I also couldn't find the file in GitHub. I also tried running it as Admin, but I got the same error.

I'm happy to be corrected if I'm doing something wrong. What's odd is that I have run this version of the scoreboard on this machine before. I don't know how it worked then and isn't working now. I deleted my previous version and downloaded a fresh copy to make sure. I still get the error.

Thank you,
Emo

**Comment by frank-weinberg** [comment]
You downloaded a source code zip instead of the compiled version. You need to download crg-scoreboard_v2023.5.zip from https://github.com/rollerderby/scoreboard/releases/latest not the zip from the Github landing page. (I know that having that link on the landing page is confusing for non-developers but unfortunately can't remove or change it.)

**Comment by Captain-Emo** [comment]
I knew I was doing something wrong. Thanks!
