### ISSUE TITLE
[BUG] Buttons display "Start jam" and "Lineup" during a jam instead of "-" and "Stop Jam", in "Clock shown after Timeout: Timeout" mode

### ISSUE THREAD

**Issue by Lucas-Mercier-tech** [rollerderby/scoreboard#700]
**Describe the bug**
If a jam is started after a timeout at the end of a period, the display of the buttons is incorrect.

**To Reproduce**
1. In Settings, put "Clock shown after Timeout" to "Timeout"
2. Start a new game, start a jam, and change the period clock to 0 second
3. End the jam
4. Start a timeout
5. Start a jam

The buttons display "Start jam" and "Lineup" despite the jam being in progress.

**Expected behavior**
The buttons should display "-" and "Stop jam".
Possibly, the "Intermission" clock should be stopped.

**Screenshots**

**Version:**
v2023.7

**If this issue occurred on a computer, please complete the following information:**
 - OS and version: [Windows 10 Home]
 - Browser [chrome 125.0.6422.78]
(Also displayed on Ubuntu 24.04 and Firefox)

**Comment by frank-weinberg** [comment]
You forgot to end the timeout. Starting a Jam straight from a Timeout is operator error. (It's still possible and will mostly work in order to minimize negative effects of operator errors.)

But while reproducing this, I discovered that if a Timeout is started straight from a Jam at 0 seconds remaining, the button labels are also wrong. So I'll leave the ticket open for that and we'll see if the Jam straight from timeout buttons can be addressed as well. But either way the fix will probably only go into v2025 and not trigger a 2023.8, given that it is only the labels and not the function of the buttons that is affected.

**Comment by frank-weinberg** [comment]
I was able to fix the buttons in the Straight from Jam to Timeout scenario but not the Timeout to Jam one.
But I changed the label during timeouts from "Start Jam" to "---" in order to make it clearer that one shouldn't use this button at this time.

Changes will be in v2025.
