### ISSUE TITLE
[2025.1_Beta1] After the end of a timeout a timeout clock is shown next to a "Lineup" label

### ISSUE THREAD

**Issue by queekusme** [rollerderby/scoreboard#710]
**Describe the bug**
When ending a timeout via the top 'End Timeout' button, the timeout clock continues to run (in the score view below the sbo operator panel it shows the correct end time).

Lineup doesn't automatically start (2023.x only), and when in 'Lineup' will show 'Lineup' on the scoreboard view but shows the timer for the timeout rather than the lineup (see image)

**To Reproduce**
1. Click 'Start Jam'
2. Click 'Stop Jam'
3. Click Official TO
4. Wait a few seconds
5. Click 'End timeout'
6. See that the correct timeout time appears in the score timeline below the operator screen
7. See the timer doesn't end correctly
9. Click the Start Button for Lineup (either when the button to show the buttons is shown or via the linup config popup)
    - Not applicable for 2025.1_Beta1
11. See the scoreboard shows Lineup but with the timer for the recent Timeout

**Expected behavior**
Timeout Clock to end at the correct time, Lineup to automatically start (2023.7 only) and it show the correct lineup clock on the scoreboard

**Screenshots**
<img width="2560" alt="Screenshot 2024-06-09 at 22 55 23" src="https://github.com/rollerderby/scoreboard/assets/4058442/b79315b5-eb6b-4d79-8c36-2de6a50bbbe9">

**Version:**
- 2023.7 through 2023.0
- 2025.1_Beta1

**If this issue occurred on a computer, please complete the following information:**
 - OS and version: MacOS 11.4
 - Browser: Chrome
 - Version: 125.0.6422.142 (Official Build) (x86_64)

**Additional context**
Tested with OTO/OR/TT and issue is consistant across all timeout types

**Comment by atkinsonm** [comment]
Check the scoreboard operator settings tab. There should be drop down for the after timeout display with options of either timeout or lineup. 

Also be advised of a change ~~coming soon~~ ^recently implemented that's relevant: https://community.wftda.org/t/wftda-officiating-procedures-update/602

> When returning from a Timeout, the scoreboard should allow the timeout clock to continue to run and go right from the timeout clock into the start of the next jam. The Jam Timer will start the next jam at either 30 seconds after the end of the timeout, or when both teams are ready, whichever is first. DO NOT start the lineup clock and stop the timeout clock.

**Comment by K-o-R** [comment]
That rule change is so stupid and clearly written by someone who never operated the scoreboard.

**Comment by queekusme** [comment]
> That rule change is so stupid and clearly written by someone who never operated the scoreboard.

Agreed, since the scoreboard is 'the source of truth' for teams, officials, spectators to know what is happening it should be displaying the correct information

**Comment by JeneralPain** [comment]
I think it's important to remember, the system was written to the standards guide released by WFTDA.If we believe something should change, it needs to be accurately fed back to the OffComm to change things. We can't drive the change to the standards. I've always "ended the timeout" only to push CRG to a "new state" but it's not needed going forward since it changes it.Sent from my iPhoneOn 10 Jun 2024, at 16:59, Queekusme ***@***.***> wrote:﻿

That rule change is so stupid and clearly written by someone who never operated the scoreboard.

Agreed, since the scoreboard is 'the source of truth' for teams, officials, spectators to know what is happening it should be displaying the correct information

**Comment by queekusme** [comment]
As an SBO I will always end a timeout manually when it ends, which is more important now as the scoreboard can be used to output IGRFs for correct inforation logging.

2025.1_Beta starts the lineup clock however does not end the timeout clock which is still shown as counting up on the display view

since this is the vew that skaters and officials use, this could be seen as confusing and may lead to people believing that the lineup has run over and taking action that further delays the start of the next jam.

it is my belief that it should show the correct timer regardless of which is correct

i.e. if 'lineup' text is shown on the display, the lineup clock should be shown, and if 'Time out' text is shown on the view then the timeout clock should be shown...

All this 'This is wrong, that is wrong' well the wrong clock is shown when lineup is showing which means something is wrong here.

Either the logic should be reverted in 2025.1_Beta1 as per 2023.x or the correct clock should be shown on the display at the correct time.

Considering the change in 2025.1_Beta1 to show the lineup clock, it seems as if that decision was already made.

Please can you decide how you want it to work and resolve as necessary.

Thank you

**Comment by frank-weinberg** [comment]
That procedure change quoted by @atkinsonm  is not coming soon, it is already in effect. (The post says "effective immediately".) The procedure says that in any regulation game we have no choice but to show a timeout clock between the end of a timeout and the start of the next jam or timeout.

At the same time the rules require that the state of the game has to be clearly visible to everyone at the game. Since the new procedures also allow the Jam Timer to leave the pivot line once the type of timeout is displayed on the scoreboard, there must be some sort of indication on the scoreboard that the game state has changed from "Timeout" to "Lineup". Since we are not allowed to change the clock as per the above procedure, changing the label next to it is the only option remaining.

I fully agree that it is stupid to display the text "Lineup" with  a timeout clock next to it. But right now it is the only way to remain compliant with both the rules and officiating procedures without deviation, as mandated for any Regulation game by the WFTDA Sanctioning Policy. I have talked to members of the WFTDA board this weekend and a meeting between the relevant people at WFTDA and myself as CRG maintainer regarding how to make sure procedures and software are aligned (including if this specific procedure is actually needed) will take place relatively soon after the Regionals are done. Thus I hope to be able to change the behaviour before a stable release of CRG v2025.


I will leave this ticket open since other people will presumably be stumbling across the same thing. Please abstain from turning this into a discussion on WFTDA rules and procedures.

**Comment by queekusme** [comment]
Just to make it easier for everyone to find:

https://static.wftda.com/officiating/wftda-officiating-procedures.pdf

4.8 When returning from a Timeout, the scoreboard should allow the timeout clock to
continue to run and go right from the timeout clock into the start of the next jam. The
Jam Timer will start the next jam at either 30 seconds after the end of the timeout, or
when both teams are ready, whichever is first. DO NOT start the lineup clock and stop
the timeout clock.

**Comment by frank-weinberg** [comment]
We are almost 3 months beyond Regionals and there has not been any activity (visible to me) towards setting up the promised meeting or any other way of getting the alignment process going.
Given this and the fact that the situation described in #767 is much easier to recover from with the clock set to "Lineup", I'll be switching the default back.

**Comment by reflexdd** [comment]
@frank-weinberg as the question was already raised in the Facebook group...
The default Setting was set back to Lineup in beta 4 but in the current release the option to choose between lineup and timeout has disappeared completely.

Was this intended?

**Comment by bullseye555** [comment]
I asked this same question in Slack to Speedy about... 5mins ago, lol

**Comment by frank-weinberg** [comment]
From the release notes of 2025.0, section "Headline Changes":

> Due to incompatibilities with other features the "Clock after Timeout" feature had to be removed.

and from the "Changes since 2025-beta4" section:

> Hide unstopped timeouts from the main display and overlay in order to reduce game impact of operator errors (https://github.com/rollerderby/scoreboard/pull/783)
    This broke showing a timeout clock after the timeout ended, so the option has been removed.
    
See also https://github.com/rollerderby/scoreboard/issues/757

**Comment by bullseye555** [comment]
What's the correct action from a CRG perspective. Stop the time out (so it
goes to Lineup on the Main Display), or just start the Jam and let the TO
clock run until the next TO starts?

**Comment by frank-weinberg** [comment]
https://github.com/rollerderby/scoreboard/wiki/Scoreboard-Operation#during-a-timeout - last bullet: "When the jam timer blows the rolling whistle to end the timeout, press the "End Timeout" button."
https://github.com/rollerderby/scoreboard/wiki/Quick-Start-Guide#controlling-the-clock - subitem "End Timeout: Click this button at the rolling whistle that ends the timeout."
