### ISSUE TITLE
[2025-beta2 FR] ePLT Go To Next Jam behaviour

### ISSUE THREAD

**Issue by bullseye555** [rollerderby/scoreboard#738]
**Is your feature request related to a problem? Please describe.**
Feedback from use of ePLT (**both teams** screen) at scrimmage over the weekend was that having to tap _Go to Next Jam_ for both teams was an extra step that could be eliminated

**Describe the solution you'd like**
In the same way there is a banner for _Go To Current Game_, either re-use the existing top-of-screen banner for _Go to Next Jam_ which will trigger **both** teams to go to next jam. This would be an as-well-as (or instead of, if easier to implement) the current _Go to Next Jam_ for both teams

**Describe alternatives you've considered**
If this isn't practical, having 2 _Go to Next Jam_ options is not a deal breaker - having a single button option is a nice-to-have

**Comment by frank-weinberg** [comment]
I've done it slightly differently: The button is between the input and sheets section in order to avoid the input section being moved on the screen. (Could be a problem when operator is about to hit a button.) And it will show up on the single team version as well, only affecting the displayed team in that case.

I did think about removing the existing button, as that would substantially simplify the code for that column, but decided against it as for large teams and/or small screens the new button could easily be out of view.
