### ISSUE TITLE
[BUG] Unable to add new ruleset

### ISSUE THREAD

**Issue by SirWhistleton-the-3rd** [rollerderby/scoreboard#748]
**Describe the bug**
Unable to create a new ruleset

**To Reproduce**
1. Go to rulesets
2. Click on New
3. Set up ruleset including Parent
4. Tick Boxes unavailable to edit rules

**Expected behavior**
Able to tick the box of the parameter and update the ruleset

**Version:**
v2025-beta2

**If this issue occurred on a computer, please complete the following information:**
 - OS and version: Windows 11
 - Browser Microsoft Edge
 - Version [127.0.2651.74 (Official build) (64-bit)

**Comment by JeneralPain** [comment]
Can we replicate this fault on chrome or Firefox? Sent from my iPhoneOn 28 Jul 2024, at 03:48, SirWhistleton-the-3rd ***@***.***> wrote:﻿
Describe the bug
Unable to create a new ruleset
To Reproduce
Steps to reproduce the behavior:

Go to rulesets
Click on New
Set up ruleset including Parent
Tick Boxes unavailable to edit rules

Expected behavior
Able to tick the box of the parameter and update the ruleset
Version:
v2025-beta2
If this issue occurred on a computer, please complete the following information:

OS and version: Windows 11
Browser Microsoft Edge
Version [127.0.2651.74 (Official build) (64-bit)
