### ISSUE TITLE
[BUG] Scoreboard Operator failing import

### ISSUE THREAD

**Issue by bullseye555** [rollerderby/scoreboard#750]
**Describe the bug**
In 2025 (dev branch as at commit https://github.com/rollerderby/scoreboard/commit/f60e7655bed1aa51f688c5cc39da46aced0901a2 ), operator import is failing using operator exported from 2023.6 and 2023.7
Operator exported from 2025 successfully imports

**To Reproduce**
1. Export an operator from a 2023 version CRG
2. Import JSON to v2025
3. Nothing imports

**Expected behavior**
Operators are successfully imported

**Screenshots**
When running via Linux, a message shows in the terminal "Updating import from version v2023.5" - this does not appear in the windows equivalent
![image](https://github.com/user-attachments/assets/e9450bd9-1d08-460b-9df2-42802d0fce84)

Exported v2023 file attached
[crg-operator-BullseyeT3.json](https://github.com/user-attachments/files/16486805/crg-operator-BullseyeT3.json)

**Version:**
2025 using the dev branch as at commit https://github.com/rollerderby/scoreboard/commit/f60e7655bed1aa51f688c5cc39da46aced0901a2 

**If this issue occurred on a computer, please complete the following information:**
 - OS and version: WIndows 11 Pro 23H2 build 22631.3958 and WSL 2 running Ubuntu
 - Browser: Chrome
 - Version 127.0.6533.89

**Comment by JeneralPain** [comment]
If there is a structure change between 2023 and 2025, this is likely why you are getting an import error.

 

I’d have to see if a debug log is generated on the failed import.

 

And I would also compare the exported operators between 2023 and 2025 for any significant structure differences.

 

From: bullseye555 ***@***.***> 
Sent: Sunday, August 4, 2024 6:09 PM
To: rollerderby/scoreboard ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rollerderby/scoreboard] [BUG] Scoreboard Operator failing import (Issue #750)

 

Describe the bug
In 2025 (dev branch as at commit  <https://github.com/rollerderby/scoreboard/commit/f60e7655bed1aa51f688c5cc39da46aced0901a2> f60e765 ), operator import is failing using operator exported from 2023.6 and 2023.7
Operator exported from 2025 successfully imports

To Reproduce
Steps to reproduce the behavior:

1.	Export an operator from a 2023 version CRG
2.	Import JSON to v2025
3.	Nothing imports

Expected behavior
Operators are successfully imported

Screenshots
When running via Linux, a message shows in the terminal "Updating import from version v2023.5" - this does not appear in the windows equivalent
image.png (view on web) <https://github.com/user-attachments/assets/e9450bd9-1d08-460b-9df2-42802d0fce84> 

Exported v2023 file attached
crg-operator-BullseyeT3.json <https://github.com/user-attachments/files/16486805/crg-operator-BullseyeT3.json> 

Version:
2025 using the dev branch as at commit  <https://github.com/rollerderby/scoreboard/commit/f60e7655bed1aa51f688c5cc39da46aced0901a2> f60e765

If this issue occurred on a computer, please complete the following information:

*	OS and version: WIndows 11 Pro 23H2 build 22631.3958 and WSL 2 running Ubuntu
*	Browser: Chrome
*	Version 127.0.6533.89

**Comment by bullseye555** [comment]
> If there is a structure change between 2023 and 2025, this is likely why you are getting an import error.
Yeah - there appears to be a structure change, but given the message from the linux screen, I suspect @frank-weinberg has coded something to pickup if it's a 2023 operator export and do some updates to import into 2025

**Comment by frank-weinberg** [comment]
The reason you're not seeing the "Updating import" message in the windows screenshot is because that is another instance of v2023 and thus no update is necessary.
And as you suspected, the conversion for these settings was missing.

**Comment by bullseye555** [comment]
> The reason you're not seeing the "Updating import" message in the windows screenshot is because that is another instance of v2023 and thus no update is necessary.
Yeah... that'd do it. Clearly got my CRG versions mixed up when testing and didn't notice I had 2023 open in Windows and not 2025.... 

Thanks for picking it up and the prompt bug fix
