### ISSUE TITLE
[BUG] Star Pass on initial pass doesn't mark 'lost' for team

### ISSUE THREAD

**Issue by queekusme** [rollerderby/scoreboard#762]
**Describe the bug**
During a game today I had Black Jammer initiate a Star pass whilst on their initial pass, when i pressed the 'Star Pass' button I noticed that 'Lost' was not automatically selected.

I've put this as a bug rather than a feature as although I don't think this ever was a thing (possibly) imho it is a quality of life thing that probably should happen

**To Reproduce**
1. Setup a game as normal
2. Start a jam
3. Click 'star pass' for a skater whilst 'ni' is still highlighted
4. See 'Lead' still not highlighted

**Expected behavior**
When 'Star Pass' is pressed when skater in initial pass 'Lost' to be selected automatically

**Screenshots**
None available, apologies

**Version:**
2023.7

**If this issue occurred on a computer, please complete the following information:**
 - Windows 11
 - Chrome Browser
 - Server running on Raspberry Pi

**Additional context**
Raspberry Pis were cleaned down between each game so should be as close to a fresh install for each game as possible

**Comment by JeneralPain** [comment]
If the star pass happens before the first initial jammer (the jammer starting the star pass), then they lose the ability for lead so that's correct.Sent from my iPhoneOn 25 Aug 2024, at 03:46, Queekusme ***@***.***> wrote:﻿
Describe the bug
During a game today I had Black Jammer initiate a Star pass whilst on their initial pass, when i pressed the 'Star Pass' button I noticed that 'Lost' was not automatically selected.
I've put this as a bug rather than a feature as although I don't think this ever was a thing (possibly) imho it is a quality of life thing that probably should happen
To Reproduce
Steps to reproduce the behavior:

Setup a game as normal
Start a jam
Click 'star pass' for a skater whilst 'ni' is still highlighted
See 'Lead' still not highlighted

Expected behavior
When 'Star Pass' is pressed when skater in initial pass 'Lost' to be selected automatically
Screenshots
None available, apologies
Version:
2023.7
If this issue occurred on a computer, please complete the following information:

Windows 11
Chrome Browser
Server running on Raspberry Pi

Additional context
Raspberry Pis were cleaned down between each game so should be as close to a fresh install for each game as possible

**Comment by queekusme** [comment]
PR Created: https://github.com/rollerderby/scoreboard/pull/763
