### ISSUE TITLE
[ePBT] Paperwork feed like SBO/ePLT

### ISSUE THREAD

**Issue by JeneralPain** [rollerderby/scoreboard#784]
**Is your feature request related to a problem? Please describe.**
Rather than the big "penalty box seated" buttons, remove them and move it to the view of the penalty box paperwork the same as we have for the existing roles like SBO/PLT.

**Describe the solution you'd like**
Change in the handling of data for the penalty box to simplify operations and also provide the running IGRF digital sheet. Also when a penalty is issued by the ePLT, the PBT/PBM only has to click on the skater number and nothing else. Remove unnecessary clicks to simplify operations.

**Describe alternatives you've considered**
I dont think there is any alternatives.

**Comment by frank-weinberg** [comment]
This would not simplify operations, it would make ePBT unusable beyond a scrimmage setting. For precise timing you need to be able to start a clock precisely when "butt hits seat". In order to do this you have to look at the skater, not at your screen. And large buttons are the only way to ensure you can reliably hit them without looking at the screen.

I also don't see the point of having the paperwork on this screen in the first place. PBT paperwork is 
1. to help time multiple skaters with a single stopwatch - we don't need this with ePBT
2. for comparing info with PLT - but ePBT and ePLT work on the same set of data, so they would always match and comparing them brings no benefit. And for comparing with paper PLT ePLT is better anyways.
