### ISSUE TITLE
Line-up Clock not starting V2025.1

### ISSUE THREAD

**Issue by AngryOgre99** [rollerderby/scoreboard#798]
When a jam runs a full 2 minutes, at the end of the jam the lineup clock does not start.

**Comment by bullseye555** [comment]
This isn't a bug @AngryOgre99 

Auto-End Jams is turned off by default in 2025.x versions
![image](https://github.com/user-attachments/assets/e1c4af0d-38ac-4078-9c6e-5235941a471f)

**Comment by AngryOgre99** [comment]
thank you.

**Comment by AngryOgre99** [comment]
I never even realized that setting was there.  I was looking for something
similar under the rules tab where you set the parameters of the games.

**Comment by frank-weinberg** [comment]
The setting is also available on the main operator screen right next to "Edit Key Control". 

But you should really consider not using it. If the JT happens to miss the call-off, Auto-End will cause additional follow-up problems because the visible lineup clock is off. (And if ePBT is used, the impact is even greater because the penalty clocks will stop while the jam is still on.)

And it also is way easier to develop a routine of "when the whistles go, press the button" instead of "when the whistles go, check the clock and make a decision if you press the button or not".

**Comment by AngryOgre99** [comment]
So, is this to say, rather than auto end jam if the 2 min jam completes by time and not call off, the operator should click the end jam button on the controller page?I ask only because I have never had to do that prior so this aspect would be new to me.Thank you.Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: frank-weinberg ***@***.***> Date: 11/18/24  9:05 AM  (GMT-08:00) To: rollerderby/scoreboard ***@***.***> Cc: AngryOgre99 ***@***.***>, Mention ***@***.***> Subject: Re: [rollerderby/scoreboard] Line-up Clock not starting V2025.1 (Issue #798) 
The setting is also available on the main operator screen right next to "Edit Key Control".
But you should really consider not using it. If the JT happens to miss the call-off, Auto-End will cause additional follow-up problems because the visible lineup clock is off. (And if ePBT is used, the impact is even greater because the penalty clocks will stop while the jam is still on.)
And it also is way easier to develop a routine of "when the whistles go, press the button" instead of "when the whistles go, check the clock and make a decision if you press the button or not".

**Comment by frank-weinberg** [comment]
Yes. The recommended procedure is to always use the "End Jam" button to end a jam, no matter when or why it was called off.

**Comment by AngryOgre99** [comment]
Ok, thanks for the clarification.
